### PR TITLE
[popover] Fix outside click after right clicking in popup

### LINKED ISSUE #2507: [popover] Right click in popover popup needs 2 outside clicks to close it
# Bug report

## Reproducible example

https://codesandbox.io/p/sandbox/dklnw3

1. Open the popover
2. Right click in the popup
3. First outside click: dismisses the system context menu, ✅
4. Second outside click does not close the popover popup
5. Needs another outside click

## Base UI version

beta-2

## Which browser are you using?

Firefox

## Which OS are you using?

Mac OS

## Which assistive tech are you using (if applicable)?

Voiceover/JAWS etc.

## Additional context

Provide any additional context that might help us identify the problem and find a solution.

### PR DESCRIPTION
**Pull request by baptisteArno**
- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/base-ui/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).

Fixes #2507

### CODE REVIEW

File: packages/react/src/floating-ui-react/hooks/useDismiss.ts [hunk 1]
```diff
@@ -626,7 +626,8 @@ export function useDismiss(
 
   const handlePressedInside = useEventCallback((event: React.MouseEvent) => {
     const target = getTarget(event.nativeEvent) as Element | null;
-    if (!contains(elements.floating, target)) {
+    const isRightClick = event.button === 2;
+    if (!contains(elements.floating, target) || isRightClick) {
```
Comment (atomiks) [inline packages/react/src/floating-ui-react/hooks/useDismiss.ts]: I guess `event.button !== 0` could also work. Do you have context on why this is needed?

Comment (michaldudak) [reply packages/react/src/floating-ui-react/hooks/useDismiss.ts]: `event.button !== 0` would actually be more correct, as it handles middle-clicks as well.

**Review by atomiks — APPROVED** [review]

**Comment by atomiks** [comment]
Looks like Dialog still has the issue

**Comment by baptisteArno** [comment]
Ok let me take a look

**Comment by baptisteArno** [comment]
My bad, wrong condition operator 🙏

**Comment by oliviertassinari** [comment]
I wonder if this doesn't deserve a regression test case.

**Comment by baptisteArno** [comment]
> I wonder if this doesn't deserve a regression test case.

You're right, will add this :)
