### PR TITLE
[switch] Add `value` prop

### LINKED ISSUE #3410: [switch] Accept `value` prop
# Bug report

## Current behavior

`Switch` currently doesn't accept `value`, unlike `Checkbox`, but both internally render `<input type="checkbox">`

### PR DESCRIPTION
**Pull request by Grafikart**
Add 'value' prop to SwitchRoot component for form submission. For instance in a project i'm working on I want the value "1" or "0".

Closes #3410

### CODE REVIEW

**Comment by atomiks** [comment]
Thanks for the contribution - I've linked the issue: #3410

I'm not sure it's this simple though: Checkbox has a `value` prop but it's a bit more involved. Though this may be due to checkboxes being able to be grouped (`CheckboxGroup`). 

```jsx
    // React <19 sets an empty value if `undefined` is passed explicitly
    // To avoid this, we only set the value if it's defined
    valueProp !== undefined
      ? { value: (groupContext ? checked && valueProp : valueProp) || '' }
      : EMPTY_OBJECT,
```

Tests would be good in any case though

**Comment by Grafikart** [comment]
@atomiks thanks, I added the same logic as the checkbox and added a test

File: packages/react/src/switch/root/SwitchRoot.tsx [hunk 1]
```diff
@@ -196,6 +199,11 @@ export const SwitchRoot = React.forwardRef(function SwitchRoot(
           },
         },
         validation.getInputValidationProps,
+        // React <19 sets an empty value if `undefined` is passed explicitly
+        // To avoid this, we only set the value if it's defined,
+        value !== undefined
+          ? { value: value }
+          : EMPTY_OBJECT,
```
Comment (atomiks) [inline packages/react/src/switch/root/SwitchRoot.tsx]:
```suggestion
        value !== undefined ? { value } : EMPTY_OBJECT,
```

File: packages/react/src/switch/root/SwitchRoot.tsx [hunk 2]
```diff
@@ -196,6 +199,9 @@ export const SwitchRoot = React.forwardRef(function SwitchRoot(
           },
         },
         validation.getInputValidationProps,
+        // React <19 sets an empty value if `undefined` is passed explicitly
+        // To avoid this, we only set the value if it's defined,
```
Comment (atomiks) [inline packages/react/src/switch/root/SwitchRoot.tsx]:
```suggestion
        // React <19 sets an empty value if `undefined` is passed explicitly
        // To avoid this, we only set the value if it's defined
```

File: packages/react/src/switch/root/SwitchRoot.tsx [hunk 3]
```diff
@@ -304,6 +310,11 @@ export interface SwitchRootProps
    * @default false
    */
   required?: boolean;
+  /**
+   * The value submitted with the form when the switch is on.
+   * By default, switches submit the value "on", matching native checkbox behavior.
+   */
+  value?: string;
```
Comment (atomiks) [inline packages/react/src/switch/root/SwitchRoot.tsx:317]: `pnpm docs:api` needs to be ran to generate the docs for this prop

There are also some lint errors to address

File: packages/react/src/switch/root/SwitchRoot.tsx [hunk 4]
```diff
@@ -304,6 +310,11 @@ export interface SwitchRootProps
    * @default false
    */
   required?: boolean;
+  /**
+   * The value submitted with the form when the switch is on.
+   * By default, switches submit the value "on", matching native checkbox behavior.
```
Comment (LukasTy) [inline packages/react/src/switch/root/SwitchRoot.tsx]:
```suggestion
   * By default, Switch submits the "on" value, matching native checkbox behavior.
```

File: packages/react/src/switch/root/SwitchRoot.test.tsx [hunk 5]
```diff
@@ -235,6 +235,25 @@ describe('<Switch.Root />', () => {
 
     expect(input).to.have.attribute('name', 'switch-name');
     expect(switchElement).not.to.have.attribute('name');
+  })
+
+  it('should set the value attribute by default', async () => {
```
Comment (LukasTy) [inline packages/react/src/switch/root/SwitchRoot.test.tsx]: Or am I missing something here? 🤔 
```suggestion
  it('should not set the value attribute by default', async () => {
```

**Review by LukasTy — COMMENTED** [review]
Thank you for the contribution. 🙏 
As James said, please run `pnpm prettier && pnpm doc:api`.

File: package.json [hunk 6]
```diff
@@ -129,5 +129,8 @@
         }
       }
     }
+  },
+  "volta": {
```
Comment (michaldudak) [inline package.json]: To remove

File: package.json [hunk 7]
```diff
@@ -129,5 +129,8 @@
...
+    "node": "24.12.0"
```
Comment (LukasTy) [inline package.json]:
```suggestion
```

File: packages/react/src/switch/root/SwitchRoot.test.tsx
Comment (LukasTy) [inline packages/react/src/switch/root/SwitchRoot.test.tsx:4]:
```suggestion
import { act, fireEvent, reactMajor, screen } from '@mui/internal-test-utils';
```

File: packages/react/src/switch/root/SwitchRoot.test.tsx [hunk 8]
```diff
@@ -237,6 +237,24 @@ describe('<Switch.Root />', () => {
     expect(switchElement).not.to.have.attribute('name');
   });
 
+  it('should not set the value attribute by default', async () => {
+    await render(<Switch.Root />);
+
+    const input = screen.getByRole('checkbox', { hidden: true });
+
+    expect(input).not.to.have.attribute('value');
```
Comment (LukasTy) [inline packages/react/src/switch/root/SwitchRoot.test.tsx:245]: React 18 tests fail due to this.
```suggestion
    // In tests on React 18, `undefined` value is retried as an empty string.
    if (reactMajor <= 18) {
      expect(input.getAttribute('value')).to.equal('');
    } else {
      expect(input).not.to.have.attribute('value');
    }
```

File: packages/react/src/switch/root/SwitchRoot.tsx [hunk 9]
```diff
@@ -169,6 +171,7 @@ export const SwitchRoot = React.forwardRef(function SwitchRoot(
           id: hiddenInputId,
           name,
           required,
+          value,
```
Comment (atomiks) [inline packages/react/src/switch/root/SwitchRoot.tsx]:
```suggestion
          required,
```

File: packages/react/src/switch/root/SwitchRoot.test.tsx [hunk 10]
```diff
@@ -237,6 +237,29 @@ describe('<Switch.Root />', () => {
...
+    await render(<Switch.Root />);
+
+    const input = screen.getByRole('checkbox', { hidden: true });
+
+    // In tests on React 18, `undefined` value is retried as an empty string.
+    if (reactMajor <= 18) {
+      expect(input.getAttribute('value')).to.equal('');
+    } else {
+      expect(input).not.to.have.attribute('value');
+    }
```
Comment (atomiks) [inline packages/react/src/switch/root/SwitchRoot.test.tsx]:
```suggestion
    expect(input).not.to.have.attribute('value');
```

File: packages/react/src/switch/root/SwitchRoot.test.tsx [hunk 11]
```diff
@@ -1,7 +1,7 @@
 import * as React from 'react';
 import { expect } from 'chai';
 import { spy } from 'sinon';
-import { act, fireEvent, screen } from '@mui/internal-test-utils';
+import { act, fireEvent, reactMajor, screen } from '@mui/internal-test-utils';
```
Comment (atomiks) [inline packages/react/src/switch/root/SwitchRoot.test.tsx]:
```suggestion
import { act, fireEvent, screen } from '@mui/internal-test-utils';
```

File: packages/react/src/switch/root/SwitchRoot.test.tsx [hunk 12]
```diff
@@ -237,6 +237,25 @@ describe('<Switch.Root />', () => {
     expect(switchElement).not.to.have.attribute('name');
   });
 
+  it('should not set the value attribute by default', async () => {
+    await render(<Switch.Root />);
+
+    const input = screen.getByRole('checkbox', { hidden: true });
+
+    // In tests on React 18, `undefined` value is retried as an empty string.
+    expect(input).not.to.have.attribute('value');
```
Comment (atomiks) [inline packages/react/src/switch/root/SwitchRoot.test.tsx]:
```suggestion
    expect(input).not.to.have.attribute('value');
```
