### PR TITLE
[popups] Fix useDismiss when component is portaled into shadow DOM

### LINKED ISSUE #3603: [menu] Content doesn't close on interaction outside of popup in ShadowRoot
# Bug report

## Current behavior

https://github.com/user-attachments/assets/2f3e7d2e-5064-4973-9040-c33c8ab0887a

When menu opened (with passed ShadowRoot container to MenuPortal), it doesn't close on interaction outside of popup in ShadowRoot. But when clicking not on the ShadowRoot, it closes. 

## Expected behavior

The menu should detect that the click occurred outside its own bounds inside ShadowRoot and close automatically.

### PR DESCRIPTION
**Pull request by dmitri-gb**
This fixes #3603

`useDismiss` expects the root ancestor of the "click-outside" target to contain a "marker" (an element matching `[data-base-ui-inert]`), otherwise the click will be ignored. For components that have backdrops (modal dialogs, modal menu popups etc) this means that the backdrop must also satisfy this condition. These components include such a marker via the `InternalBackdrop` component. However, `useDismiss` uses `document.querySelectorAll` to find all these markers, which means it will not find any that live inside the shadow DOM. Passing `container={shadowRoot}` to `Dialog.Portal`, `Menu.Portal` etc where `shadowRoot` is attached to a direct child of `<body>` makes this marker invisible to `useDismiss`.

As a result, modal dialogs, menu popups etc that are portaled into a top-level ShadowRoot cannot be dismissed by a "click-outside".

There are multiple ways how this could be fixed. In theory, shadow roots could be nested multiple levels deep etc, but for the backdrop click to work we only need to find the one marker that was rendered by the component that called `useDismiss`. So I went with the smallest possible change — only inspecting the direct shadow root of the click target and appending all markers in it to the existing markers collection. The `contains` check on line 367 already pierces shadow roots, so it will see the added markers.

- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/base-ui/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).

### CODE REVIEW

File: packages/react/src/floating-ui-react/hooks/useDismiss.ts [hunk 1]
```diff
@@ -324,9 +324,13 @@ export function useDismiss(
...
       const inertSelector = `[${createAttribute('inert')}]`;
-      const markers = ownerDocument(store.select('floatingElement')).querySelectorAll(
-        inertSelector,
+      let markers = Array.from(
+        ownerDocument(store.select('floatingElement')).querySelectorAll(inertSelector),
       );
+      const targetRoot = isElement(target) ? target.getRootNode() : null;
+      if (targetRoot instanceof ShadowRoot) {
+        markers = markers.concat(Array.from(targetRoot.querySelectorAll(inertSelector)));
+      }
```
Comment (atomiks) [inline packages/react/src/floating-ui-react/hooks/useDismiss.ts]: There's an `isShadowRoot` util

**Comment by atomiks** [comment]
`InternalBackdrop` manually sets `data-base-ui-inert=""` on its JSX, but the user-provided Backdrops don't. And I'm assuming this actually regressed after fixing https://github.com/mui/base-ui/issues/2940 because the user-provided Backdrop now renders on top of the InternalBackdrop.

Given this change, could we remove the `data-base-ui-inert=""` prop from InternalBackdrop?

**Comment by dmitri-gb** [comment]
Hmm, no, I don't think we can remove it. We actually rely on it. This is precisely the marker that is found in `useDismiss`. I don't think it matters which backdrop renders on top, it only matters that the marker (InternalBackdrop) exists in the same shadow root where the user backdrop (the click target) is.

**Review by atomiks — APPROVED** [review]
Thanks for the contribution @dmitri-gb!
