### PR TITLE
[combobox] Take into account `isItemEqualToValue` when selecting an option in multiple mode

### LINKED ISSUE #2892: [combobox] Selection does not take into account `isItemEqualToValue` and `multiple` is `true`
# Bug report

## Current behavior

Selecting the same option in a Combobox with `multiple:  true` appends said option to the current selected values, thus creating duplicates when you use objects which do not maintain referential integrity (e.g `Proxy` values through `valtio`) which I think is okay, but when using the `isItemEqualToValue` property, the behaviour stays the same.

## Expected behavior

Selecting the same option should deselect it if the `isItemEqualToValue` result is evaluated to `true` for that option.

## Reproducible example

[CodeSandbox repro](https://codesandbox.io/p/devbox/cold-fast-y96r3g?file=%2Fsrc%2FApp.tsx&workspaceId=ws_RRJobaGRBhfDBJFVKHJUux)

## Base UI version

v1.0.0-beta.4

## Which browser are you using?

Chrome

## Which OS are you using?

Mac OS

## Which assistive tech are you using (if applicable)?

N/A.

## Additional context

Going through the code, I suspect [this](https://github.com/mui/base-ui/blob/67811d07c56cbdfb722de431a538ae36e1804cc8/packages/react/src/combobox/root/ComboboxRootInternal.tsx#L717) may be the line which should take into account the function defined through the `isItemEqualToValue` property (currently uses `includes`).

I can open a PR with this change if there isn't any more context that is affected by this.

Thank you!

### PR DESCRIPTION
**Pull request by epr3**
Fixes #2892.

- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/base-ui/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).

### CODE REVIEW

**Comment by atomiks** [comment]
Thanks for the contribution! There's a test suite with `describe('prop: isItemEqualToValue'` for `ComboboxRoot` to test the behavior

It looks like Select correctly handles this in multiple mode, but adding a similar test for it would be good too

File: packages/react/src/combobox/root/ComboboxRootInternal.tsx [hunk 1]
```diff
@@ -714,9 +714,13 @@ export function ComboboxRootInternal<Value = any, Mode extends SelectionMode = '
...
         const currentSelectedValue = Array.isArray(selectedValue) ? selectedValue : [];
-        const isCurrentlySelected = currentSelectedValue.includes(value);
+        const isCurrentlySelected = itemIncludes(
+          currentSelectedValue,
+          value,
+          store.state.isItemEqualToValue,
+        );
         const nextValue = isCurrentlySelected
-          ? currentSelectedValue.filter((v) => v !== value)
+          ? currentSelectedValue.filter((v) => !store.state.isItemEqualToValue(v, value))
```
Comment (atomiks) [inline packages/react/src/combobox/root/ComboboxRootInternal.tsx]: The `removeItem` util is used by Select here

Comment (epr3) [reply packages/react/src/combobox/root/ComboboxRootInternal.tsx]: Fixed
