### PR TITLE
[combobox] Improved focus behavior for disabled and readOnly cases.

### LINKED ISSUE #4041: [combobox] Chip is focusable when Root is disabled
# Bug report

## Current behavior

When `Combobox.Root` is disabled, `Combobox.Chip` is focusable when clicked.

https://github.com/user-attachments/assets/20a0614b-6faf-402f-a495-f2e04ac0a8a6

(`document.activeElement` is the chip element)

## Expected behavior

`Combobox.Chip` is not focusable when the combobox is disabled.

## Reproducible example

https://stackblitz.com/edit/pfvwvdge?file=src%2FApp.tsx

## Base UI version

1.1.0

## Which browser are you using?

Chrome

## Which OS are you using?

Mac OS

### PR DESCRIPTION
**Pull request by jijiseong**
Fixes #4041

## Summary
Improved focus behavior for disabled and readOnly cases on ComboboxChip click.

When the prop is:
- `disabled`: the chip should not receive focus
- `readOnly`: the chip should receive focus

## Changes

- Add tests for `disabled`
- Add tests for `readOnly`
- Call `preventDefault` when `disabled`

- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/base-ui/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).

### CODE REVIEW

File: packages/react/src/combobox/chip/ComboboxChip.tsx [hunk 1]
```diff
@@ -114,7 +114,11 @@ export const ComboboxChip = React.forwardRef(function ComboboxChip(
           }
         },
         onMouseDown(event) {
-          if (disabled || readOnly) {
+          if (readOnly) {
+            return;
+          }
+          if (disabled) {
+            event.preventDefault();
             return;
```
Comment (atomiks) [inline packages/react/src/combobox/chip/ComboboxChip.tsx:124]: You should be able to move `event.preventDefault()` above `if (disabled)` so there aren't two calls (and just early-return for `if (disabled)`)

Comment (jijiseong) [reply packages/react/src/combobox/chip/ComboboxChip.tsx:124]: Tankyou for reveiw.
I resolved this.
