### PR TITLE
[avatar] Remove fallback transition logic and premature image display

### LINKED ISSUE #4109: [avatar] Incorrect Image/Fallback behaviour
# Bug report

## Current behavior

`<Avatar.Image />` is mounted while the image is still loading. At the same time, `<Avatar.Fallback />` is still in place, causing layout shifts.

## Expected behavior

`<Avatar.Image />` only mounts when image is loaded (similar to v1.1.0).

## Reproducible example

https://stackblitz.com/edit/sb1-fkfxj8ab

## Base UI version

v1.2.0

## Which browser are you using?

Chrome/Safari

## Which OS are you using?

Mac OS

### PR DESCRIPTION
**Pull request by atomiks**
- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/base-ui/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).

Setting visibility of the image to include `imageLoadingStatus === 'loading'` causes the image to show prematurely. Additionally, transitioning the fallback component out is not particularly useful and regresses layout cases where the expectation is that only one is mounted at a time.

Fixes #4109 (https://stackblitz.com/edit/sb1-urlzxstp?file=package.json,src%2FApp.tsx)

Image transition remains the same once it's loaded: https://deploy-preview-4110--base-ui.netlify.app/experiments/transition-attrs. If it hasn't been loaded yet (and not in the cache), it may not appear to play if its duration is short, as the image progressively loads in so it plays just before painting. For speed, this is likely preferable.

### CODE REVIEW

File: packages/react/src/avatar/fallback/AvatarFallback.tsx [hunk 1]
```diff
@@ -32,51 +23,29 @@ export const AvatarFallback = React.forwardRef(function AvatarFallback(
...
-  if (!mounted) {
-    return null;
-  }
-
   return element;
 });
 
-export interface AvatarFallbackState extends AvatarRoot.State {
-  transitionStatus: TransitionStatus;
-}
```
Comment (atomiks) [inline packages/react/src/avatar/fallback/AvatarFallback.tsx:79]: This was undocumented (in 1.2.0), should be safe to revert.

File: packages/react/src/avatar/fallback/AvatarFallback.tsx [hunk 2]
```diff
@@ -32,51 +23,29 @@ export const AvatarFallback = React.forwardRef(function AvatarFallback(
...
-
   React.useEffect(() => {
     if (delay !== undefined) {
       timeout.start(delay, () => setDelayPassed(true));
     }
     return timeout.clear;
   }, [timeout, delay]);
 
-  const state: AvatarFallback.State = {
+  const state: AvatarRoot.State = {
```
Comment (LukasTy) [inline packages/react/src/avatar/fallback/AvatarFallback.tsx]:
```suggestion
  const state: AvatarFallbackState = {
```
