### PR TITLE
[combobox] Support drag-to-select

### LINKED ISSUE #3086: [combobox] Combobox with trigger does not support click and drag to select
# Bug report

## Current behavior

If Combobox is used with Combobox.Trigger, it does not support the click and drag to select functionality.
 
## Expected behavior

The Select component supports that a user can click on the trigger button 
and then drag the mouse down to select an item: ([Example](https://base-ui.com/react/components/select#multiple-selection))

I would expect the Combobox to behave the same, but it doesn't: ([Example](https://base-ui.com/react/components/combobox#input-inside-popup))

## Base UI version

1.0.0-beta.4

## Which browser are you using?

Chrome

## Which OS are you using?

Mac OS

### PR DESCRIPTION
**Pull request by atomiks**
- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/base-ui/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).

Closes #3086

### CODE REVIEW

File: packages/react/src/combobox/item/ComboboxItem.tsx [hunk 1]
```diff
@@ -154,24 +168,33 @@ export const ComboboxItem = React.memo(
...
-          store.state.requestSubmit();
-        } else {
-          selectItem();
+        if (
+          disabled ||
+          readOnly ||
+          event.button !== 0 ||
+          pointerStartedOnItem ||
+          !highlighted ||
+          !store.state.inputInsidePopup
```
Comment (mj12albert) [inline packages/react/src/combobox/item/ComboboxItem.tsx]: Just wondering could this also work for input-outside-popup? If the pointer starts at the smaller trigger, not the input

Comment (atomiks) [reply packages/react/src/combobox/item/ComboboxItem.tsx]: Possibly, though it feels a bit inconsistent for it to work only on the trigger with that layout/pattern

Comment (LukasTy) [reply packages/react/src/combobox/item/ComboboxItem.tsx]: I agree with the proposal.
Seems strange to support this only on the popup mode, whereas regular `Combobox` closely resembles `Select`, but does not allow this behavior.

If we keep this behavior as is, then maybe the trigger drag -> move away behavior should change in regular behavior?
It seems slightly strange now. 🤷 

https://github.com/user-attachments/assets/cef40caf-3f99-4cdd-a4ee-4a42a0d3b308

Comment (atomiks) [reply packages/react/src/combobox/item/ComboboxItem.tsx]: Dragging on the input selects the text (if you had some in the input in that recording) though, so there's a functional difference there. Pretty sure no one is going to notice any of this though.

I removed the `mouseup` drag out behavior to match the input

**Review by LukasTy — APPROVED** [review]
Looks great, especially after the tiny fix. 👌

File: packages/react/src/combobox/item/ComboboxItem.tsx (hunk 1 above)
Comment (mj12albert) [reply packages/react/src/combobox/item/ComboboxItem.tsx]: OK I don't think it's hugely important now, but would be nice to have later ~

RA let's you single-pointer the trigger in this layout: https://react-spectrum.adobe.com/react-aria/ComboBox.html#example

Also maybe because it's styled it more distinctly from the input, seems like this interaction would be more discoverable

Comment (atomiks) [reply packages/react/src/combobox/item/ComboboxItem.tsx]: Hmm fair enough, the styled trigger does make it more clear there. I think we can unconditionally allow drags on both the trigger and input (even if it selects text) for consistency across both, but leave the `cancel-open` exclusive to the `input-inside-popup` layout

**Comment by LukasTy** [comment]
Is it expected that releasing the mouse outside of the Popup closes the Popup in case of https://deploy-preview-3167--base-ui.netlify.app/react/components/combobox#input-inside-popup, but doesn't when used with an input? 🤔

**Comment by atomiks** [comment]
@LukasTy yeah so it's consistent with the input: https://github.com/mui/base-ui/pull/3167#discussion_r2520737844
