### PR TITLE
[tabs] Add transition attributes to `<Tabs.Panel>` part

### LINKED ISSUE #3870: [tabs] `data-starting-style` and `data-ending-style` not getting applied to Panel
# Bug report

## Current behavior

The `Tabs.Panel` component does not apply the `data-starting-style` attribute upon mounting or the `data-ending-style` attribute during the unmounting phase. This prevents CSS transitions and animations from triggering correctly when switching between tabs.

## Expected behavior

The `Tabs.Panel` should provide `data-starting-style` when it enters the DOM and `data-ending-style` before it is removed (when used with an animation handler or transition), consistent with other animateable primitives in Base UI.

## Reproducible example

[Tabs Test](https://stackblitz.com/edit/vitejs-vite-mzc1zp8l?file=src%2FApp.tsx&terminal=dev)

## Base UI version

v1.1.0

## Which browser are you using?

Helium (Chromium) & Firefox

## Which OS are you using?

Mac OS

## Additional context

The absence of these attributes makes it difficult to implement entry/exit animations for tab content. Since `Tabs.Panel` handles its own visibility/mounting logic, it should support these states to align with the library's animation patterns.

### PR DESCRIPTION
**Pull request by atomiks**
- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/base-ui/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).

Closes #3870

https://deploy-preview-3880--base-ui.netlify.app/experiments/tabs-animations

### CODE REVIEW

File: docs/src/app/(private)/experiments/tabs-animations.tsx [hunk 1]
```diff
@@ -0,0 +1,110 @@
...
+    title: 'Activity',
+    description: 'Review recent changes and confirm deployment timings.',
+  },
+  {
+    title: 'Settings',
+    description: 'Adjust notifications, access, and panel behaviors.',
+  },
+];
+
+export default function TabsAnimationsExperiment() {
```
Comment (mj12albert) [inline docs/src/app/(private)/experiments/tabs-animations.tsx:32]: The current transition is really fast 😅 

Can it be like a carousel? e.g. https://motion.dev/tutorials/react-smooth-tabs

Comment (atomiks) [reply docs/src/app/(private)/experiments/tabs-animations.tsx:32]: Yeah it looks bad, but I wasn't really trying to make it look nice, just a visual test to make sure it works.
I can update it, though
