### PR TITLE
[popups] Fix close toggle when rendering non-native button

### LINKED ISSUE #2065: [popover] Does not toggle closed when rendering non-native `<button>` trigger
# Bug report

This likely applies to other components as well.

## Current behavior

`Popover.Trigger` is rendered as a `<div>`:

- Open with <kbd>Enter</kbd>
- <kbd>Shift+Tab</kbd> to tab back to the button
- <kbd>Enter</kbd>
- Doesn't toggle closed

## Expected behavior

Has the same behavior as when rendering a `<button>`.

## Reproducible example

https://codesandbox.io/p/sandbox/6l9c5j

## Base UI version

1.0.0-beta.0

### PR DESCRIPTION
**Pull request by atomiks**
Closes #2065

### CODE REVIEW

File: packages/react/src/utils/floating-ui/useClick.ts [hunk 1]
```diff
@@ -100,12 +100,13 @@ export function useClick(context: FloatingRootContext, props: UseClickProps = {}
...
+        const openEvent = dataRef.current.openEvent;
+
         const nextOpen = !(
           open &&
           toggle &&
-          (dataRef.current.openEvent && stickIfOpen
-            ? dataRef.current.openEvent.type === 'click' ||
-              dataRef.current.openEvent.type === 'mousedown'
+          (openEvent && stickIfOpen
+            ? ['click', 'mousedown', 'keydown', 'keyup'].includes(openEvent.type)
```
Comment (flaviendelangle) [inline packages/react/src/utils/floating-ui/useClick.ts]: I think Romain would prefer to avoid arrays here :laughing: 
To keep the lise of `||` as before, or at least to have a `Set` outside of the function to avoid `O(n)`

Comment (atomiks) [reply packages/react/src/utils/floating-ui/useClick.ts]: Yeah I knew 😄  - I just figured since it's a discrete click event that fires infrequently, the perf concerns are not an issue

Comment (michaldudak) [reply packages/react/src/utils/floating-ui/useClick.ts]: I don't think there will be any significant difference for just 4 elements. One thing I'd suggest, though is to have a constant array, not define it every time the handler runs.

**Review by michaldudak — APPROVED** [review]
