### PR TITLE
[tabs] Fix keyboard navigation involving disabled Tabs

### LINKED ISSUE #1442: [Tabs] Arrow keys cannot navigate to disabled Tabs
Repro: https://codesandbox.io/p/sandbox/tender-bassi-w74kv9

`Tabs.Tab` are intentionally focusable when disabled. It's possible to initially Tab into the first disabled Tab, but subsequent arrow left/right keys will not move focus to other disabled Tabs (or back to the first one)

`disabledIndices` needs to be used to properly handle focusable-when-disabled items that are also composite (roving focus) items: https://github.com/mui/base-ui/blob/master/packages/react/src/composite/root/useCompositeRoot.ts#L57-L58

This is used in https://github.com/mui/base-ui/pull/1349

### PR DESCRIPTION
**Pull request by mj12albert**
Fixes https://github.com/mui/base-ui/issues/1442

Before: https://codesandbox.io/p/sandbox/tender-bassi-w74kv9

After: https://codesandbox.io/p/devbox/restless-framework-g3j43t?file=%2Fsrc%2FApp.tsx

Tabs are intentionally focusable when disabled, so it should be possible to move focus to disabled Tabs using the arrow keys. The disabled state should only disable tab activation.

- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/base-ui/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).

### CODE REVIEW

**Comment by mj12albert** [comment]
`activateOnFocus` complicates this, might need to have separate states for "highlighted index" and "selected index" since they could be different

File: packages/react/src/tabs/list/TabsList.tsx [hunk 1]
```diff
@@ -94,6 +94,7 @@ const TabsList = React.forwardRef(function TabsList(
         onHighlightedIndexChange={setHighlightedTabIndex}
         onMapChange={setTabMap}
         render={renderElement()}
+        disabledIndices={[]}
```
Comment (michaldudak) [inline packages/react/src/tabs/list/TabsList.tsx:97]: Do not recreate the array on each render.

File: packages/react/src/tabs/tab/useTabsTab.ts [hunk 2]
```diff
@@ -58,11 +58,15 @@ function useTabsTab(parameters: useTabsTab.Parameters): useTabsTab.ReturnValue {
     return valueParam === selectedTabValue;
   }, [index, selectedTabValue, valueParam]);
 
-  // when activateOnFocus is `true`, ensure the active item in Composite's roving
-  // focus group matches the selected Tab
+  const selectedValueSyncedWithHighlightedTabIndexRef = React.useRef(false);
```
Comment (michaldudak) [inline packages/react/src/tabs/tab/useTabsTab.ts:61]: It's a mouthful :)
But too long is much better than too short, so let's leave it.

**Review by michaldudak — COMMENTED** [review]
:+1: I haven't found any issues in behavior.

File: packages/react/src/tabs/list/TabsList.tsx (hunk 1 above)
Comment (mj12albert) [reply packages/react/src/tabs/list/TabsList.tsx]: Fixed!

File: packages/react/src/tabs/tab/useTabsTab.ts (hunk 2 above)
Comment (mj12albert) [reply packages/react/src/tabs/tab/useTabsTab.ts]: this is all within a few lines so I shortened it by 12 chars 😅
`isSelectionSyncedWithHighlightRef`

**Review by michaldudak — APPROVED** [review]
