### PR TITLE
[select] Move item anchoring prop to `Positioner`

### LINKED ISSUE #1710: [docs][Select] Update `Positioner` and `anchor` prop descriptions
# Bug report

`Select` inherits the type description that's common to all `Positioner`s, but it acts special by default due to `alignItemToTrigger=true`.

> Positioner
Positions the select menu popup against the trigger. Renders a `<div>` element.

Image

### LINKED ISSUE #1711: [Select] Move `alignItemToTrigger` from `Root` to `Positioner`
# Bug report

The previous implementation required the prop to be on the `Root`, but this is no longer the case with the latest one, as it can exist on `Positioner` instead which makes more sense in the API.

@DiegoAndai @aarongarciah you mentioned possibly changing the name, which we could also do simultaneously here.

An actual proper description of the behavior is more like:

`<Select.Positioner alignSoThatSelectedItemTextIsOverTriggerValueText>`

Which is obviously unrealistically verbose, but is more accurate as the prop aligns the `Positioner` element, not the `Item` element, so the selected item text inside of it _visually appears_ directly aligned with the `Trigger` `Value` text.  

It also disables the other anchoring-related props and enters a "special positioning mode"

```jsx
<>
  <Select.Positioner align="selected" />
  <Select.Positioner overlayTriggerValue />
  <Select.Positioner alignToTrigger />
  <Select.Positioner anchorMode="selected-item|trigger" />
  <Select.Positioner positioningMode="selected-item|trigger" />
</>
```

### PR DESCRIPTION
**Pull request by atomiks**
1. Removes `alignItemToTrigger` prop from `Root`, to be configured on `Positioner` instead
2.  Changes the boolean prop name to `alignItemWithTrigger` (`To` -> `With`)

Closes #1710
Closes #1711

### CODE REVIEW

File: packages/react/src/select/item/useSelectItem.ts [hunk 1]
```diff
@@ -152,7 +152,7 @@ export function useSelectItem(params: useSelectItem.Parameters): useSelectItem.R
                 cursorMovementTimerRef.current = -1;
               }
 
-              // With `alignItemToTrigger`, avoid re-rendering the root due to `onMouseLeave`
+              // With `anchor="item"`, avoid re-rendering the root due to `onMouseLeave`
```
Comment (michaldudak) [inline packages/react/src/select/item/useSelectItem.ts:155]:
```suggestion
              // With `anchorMode="overlap-trigger"`, avoid re-rendering the root due to `onMouseLeave`
```

File: packages/react/src/select/root/useSelectRoot.ts [hunk 2]
```diff
@@ -243,7 +225,7 @@ export function useSelectRoot<T>(params: useSelectRoot.Parameters<T>): useSelect
       setActiveIndex(nextActiveIndex);
     },
     // Implement our own listeners since `onPointerLeave` on each option fires while scrolling with
-    // the `alignItemToTrigger` prop enabled, causing a performance issue on Chrome.
+    // the `anchor="item"`, causing a performance issue on Chrome.
```
Comment (michaldudak) [inline packages/react/src/select/root/useSelectRoot.ts:228]:
```suggestion
    // the `anchorMode="overlap-trigger"`, causing a performance issue on Chrome.
```

**Review by michaldudak — APPROVED** [review]
