### PR TITLE
[combobox][select] Align multiple values label resolution in `Value` component

### LINKED ISSUE #3229: [select] `Select.Value` does not consult `items` for multi array values (`multiple`)
# Bug report

Currently, `Select.Value` does not return correct labels when used with `<Select.Root items={[]} />`:

```jsx
const items = [
  {
    value: "apple",
    label: "Apple",
  },
  {
    value: "banana",
    label: "Banana",
  },
  {
    value: "cherry",
    label: "Cherry",
  },
  {
    value: "orange",
    label: "Orange",
  },
];

<Select.Root items={items} multiple>
  <Select.Trigger>
    <Select.Value />
  </Select.Trigger>

  <Select.Portal>
      <Select.Positioner>
        <Select.Popup>
          <Select.List>
           {items.map((item) => (
            <Select.Item value={item.value}>{item.label}</Select.Item>
           )}
          </Select.List>
        </Select.Popup>
      </Select.Positioner>
    </Select.Portal>
</Select.Root>
```

`Select.Value` would show "apple, banana, cherry, orange" instead of "Apple, Banana, Cherry, Orange"

However, this works:

```jsx
const items = [
  {
    value: "apple",
    label: "Apple",
  },
  {
    value: "banana",
    label: "Banana",
  },
  {
    value: "cherry",
    label: "Cherry",
  },
  {
    value: "orange",
    label: "Orange",
  },
];

<Select.Root multiple>
  <Select.Trigger>
    <Select.Value />
  </Select.Trigger>

  <Select.Portal>
      <Select.Positioner>
        <Select.Popup>
          <Select.List>
           {items.map((item) => (
            <Select.Item value={item}>{item.label}</Select.Item>
           )}
          </Select.List>
        </Select.Popup>
      </Select.Positioner>
    </Select.Portal>
</Select.Root>
```

`Select.Value` correctly shows "Apple, Banana, Cherry, Orange"

## Current behavior

As above

## Expected behavior

`Select.Value` should consistently show correct label and respect `items`.

## Reproducible example

N/A

## Base UI version

1.0.0-beta.5 (#3210)

## Which browser are you using?

Edge

## Which OS are you using?

MacOS

## Which assistive tech are you using (if applicable)?

N/A

## Additional context

The function `resolveMultipleLabels` would need to accept `items` as one of the arguments to make this work:

https://github.com/mui/base-ui/blob/49cfd5ec722a92a182f193cdc1f3f76e032785fb/packages/react/src/utils/resolveValueLabel.tsx#L114-L122

### PR DESCRIPTION
**Pull request by atomiks**
- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/base-ui/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).

This prints the labels instead of the raw values in cases where you aren't using a custom `children` function

Fixes #3229 
Closes #3678

### CODE REVIEW

File: packages/react/src/utils/resolveValueLabel.tsx [hunk 1]
```diff
@@ -112,11 +112,20 @@ export function resolveSelectedLabel(
...
+  values: any[],
+  items: ItemsInput,
   itemToStringLabel?: (item: any) => string,
-): string {
-  if (!Array.isArray(values) || values.length === 0) {
-    return '';
-  }
-  return values.map((v) => stringifyAsLabel(v, itemToStringLabel)).join(', ');
+): React.ReactNode {
+  const labels = values.map((v) => resolveSelectedLabel(v, items, itemToStringLabel));
```
Comment (oliviertassinari) [inline packages/react/src/utils/resolveValueLabel.tsx]:
```suggestion
  const labels = values.map((value) => resolveSelectedLabel(value, items, itemToStringLabel));
```
