### PR TITLE
[composites] Stop event propagation

### LINKED ISSUE #1759: [toolbar] Prevent navigation when arrow keys are pressed on an item in a popup in a toolbar
Currently `Composite` ignores any keypresses from inside popups to prevent toolbar navigation, which doesn't work for Menubar and Navigation Menu, or other composite components inside the popup: https://github.com/mj12albert/base-ui/blob/7ce819e138b5e06ef3657ed500abab2d0efa2bd0/packages/react/src/composite/root/useCompositeRoot.ts#L158-L161

Components that use the same keys (arrow keys, Home+End) should `event.stopPropgation()` in their keydown handlers instead:
- Toggle/Toggle group
- ~Slider~ done
- Radio group
- Number field
- Button/trigger components (useButton?)

### PR DESCRIPTION
**Pull request by atomiks**
Fixes #1759

Triggers preview: https://deploy-preview-1871--base-ui.netlify.app/experiments/toolbar/triggers

- Inside `Dialog`/`AlertDialog`, it prevents composite behavior from escaping itself. `Popover`/anything that doesn't trap focus or close when focus escapes it allows it
- Tabs and any other composite works inside a Dialog/Popover correctly

### CODE REVIEW

File: packages/react/src/number-field/input/NumberFieldInput.tsx [hunk 1]
```diff
@@ -1,6 +1,6 @@
 'use client';
 import * as React from 'react';
-import { useModernLayoutEffect } from '@floating-ui/react/utils';
+import { useModernLayoutEffect, stopEvent } from '@floating-ui/react/utils';
```
Comment (mj12albert) [inline packages/react/src/number-field/input/NumberFieldInput.tsx:3]: Shouldn't this import from the local utils?

File: packages/react/src/tabs/root/TabsRoot.test.tsx [hunk 2]
```diff
@@ -1062,4 +1064,84 @@ describe('<Tabs.Root />', () => {
       expect(root).to.have.attribute('data-activation-direction', 'up');
     });
   });
+
+  describe('popups', () => {
```
Comment (mj12albert) [inline packages/react/src/tabs/root/TabsRoot.test.tsx:1068]: Maybe we could consider grouping these tests with setups involving other components in `/packages/react/test/integrationTests/` or something like that? CC @michaldudak

File: packages/react/src/number-field/input/NumberFieldInput.tsx (hunk 1 above)
Comment (atomiks) [reply packages/react/src/number-field/input/NumberFieldInput.tsx:3]: Not strictly necessary, for some of them I did for backwards-compat throughout the codebase

**Review by mj12albert — APPROVED** [review]
Looks good 👍
