### PR TITLE
[Dialog, AlertDialog] Fix trigger issues

### LINKED ISSUE #618: [Dialog] In Safari, focus isn't returned to the trigger when dialog is closed
### Steps to reproduce

Link to live example: 
https://master--base-ui.netlify.app/components/react-dialog/

### Current behavior

Focus is returned to the start of the document, apparently

### Expected behavior

Focus is returned to the trigger

### Context

_No response_

### Your environment

Safari 17.6

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: safari, focus, return, trigger, close, dialog, modal

### LINKED ISSUE #619: [Dialog] Clicking the trigger doesn't close non-modal dialogs
### Steps to reproduce

Link to live example:
https://codesandbox.io/p/sandbox/2ny6h6?file=%2Fsrc%2FApp.tsx%3A8%2C46

Click the trigger multiple times.

### Current behavior

When dialog is open, dialog popup re-opens when clicking the trigger

### Expected behavior

When dialog is open, dialog popup should close when clicking the trigger

### Context

_No response_

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: dialog, non-modal, trigger, close

### PR DESCRIPTION
**Pull request by michaldudak**
Refactored the implementation of the Dialog to be more in line with other popup-like components by delegating the trigger logic to Floating UI.

This fixes two issues:
fixes #618
fixes #619

### CODE REVIEW

File: packages/mui-base/src/AlertDialog/Backdrop/AlertDialogBackdrop.tsx [hunk 1]
```diff
@@ -38,17 +38,12 @@ const AlertDialogBackdrop = React.forwardRef(function AlertDialogBackdrop(
   forwardedRef: React.ForwardedRef<HTMLDivElement>,
 ) {
   const { render, className, keepMounted = false, ...other } = props;
-  const { open, hasParentDialog, setBackdropPresent, animated } = useAlertDialogRootContext();
-
-  const handleMount = React.useCallback(() => setBackdropPresent(true), [setBackdropPresent]);
```
Comment (michaldudak) [inline packages/mui-base/src/AlertDialog/Backdrop/AlertDialogBackdrop.tsx:43]: I didn't bother refactoring this as we won't need this logic anyway after https://github.com/mui/base-ui/issues/623

**Comment by atomiks** [comment]
In Safari:

- Under the `Nested` section demo, focus the `Open` trigger with <kbd>Tab</kbd>/keyboard and click with <kbd>Enter</kbd>
- Press <kbd>Escape</kbd>
- Scroll back to the top introduction demo
- With your pointer, click the trigger
- Press <kbd>Escape</kbd>
- Focus moves back to the `Nested` open trigger incorrectly, not the intro trigger

**Comment by michaldudak** [comment]
Safari should work fine now.

**Review by vladmoroz — APPROVED** [review]

**Review by atomiks — APPROVED** [review]
