### PR TITLE
[composites] Avoid double `useRenderElement` passes

### LINKED ISSUE #2255: [toggle][togglegroup] render function receives only part of the necessary props
# Bug report

## Current behavior

The keyboard navigation for toggle group is broken if I use only those props that render function provides.

## Expected behavior

Props from render function should be enough for the work of keyboard navigation.

## Reproducible example

https://codesandbox.io/p/devbox/damp-wind-j72vfx?workspaceId=ws_8iqbh1gg1GcLonjY38LEti
(just focus on any item and try navigate through keyboard arrows)

## Base UI version

1.0.0-beta.1

## Which browser are you using?

Chrome

## Which OS are you using?

Mac OS

## Which assistive tech are you using (if applicable)?

Voiceover/JAWS etc.

## Additional context

I spent about two hours to figure out where the problem is. The element that is returned from the function is additionally added with props, such as another ref, some on-handlers and a tabindex. But I can't make a universal, independent and normally typed component because of this.

### PR DESCRIPTION
**Pull request by atomiks**
- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/base-ui/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).

Fixes #2255 by avoiding two `useRenderElement` passes

### CODE REVIEW

**Comment by mj12albert** [comment]
Using the `CompositeRoot` component would also have the same double render issue? e.g. https://github.com/mui/base-ui/blob/master/packages/react/src/radio-group/RadioGroup.tsx#L224-L229

**Comment by atomiks** [comment]
@mj12albert great point. I think maybe we need to "defer" the rendering to the `Composite{Root,Item}` components by forwarding the props to it instead of using `useRenderElement` before rendering it. (`CompositeRoot` less easy to inline in each component that renders it compared to the `Item` one)

File: packages/react/src/composite/root/CompositeRoot.tsx [hunk 1]
```diff
@@ -8,16 +8,22 @@ import { useRenderElement } from '../../utils/useRenderElement';
...
  */
-export function CompositeRoot<Metadata extends {}>(componentProps: CompositeRoot.Props<Metadata>) {
+export function CompositeRoot<Metadata extends {}, State extends Record<string, any>>(
+  componentProps: CompositeRoot.Props<Metadata, State>,
+) {
   const {
     render,
     className,
+    refs = EMPTY_ARRAY,
+    props = EMPTY_ARRAY,
```
Comment (romgrk) [inline packages/react/src/composite/root/CompositeRoot.tsx:24]: `null` or `undefined` would be more efficient as default values, array `ref` makes `useRenderElement` use `useForkRefN`.

File: packages/react/src/composite/item/CompositeItem.tsx [hunk 2]
```diff
@@ -3,27 +3,46 @@ import * as React from 'react';
...
-  const { render, className, itemRef = null, metadata, ...elementProps } = componentProps;
+export function CompositeItem<Metadata, State extends Record<string, any>>(
+  componentProps: CompositeItem.Props<Metadata, State>,
+) {
+  const {
+    render,
+    className,
+    state = EMPTY_OBJECT as State,
+    props = EMPTY_ARRAY,
+    refs = EMPTY_ARRAY,
```
Comment (romgrk) [inline packages/react/src/composite/item/CompositeItem.tsx:20]: It would be nice to standardize the API of the `refs` prop with `useRender` and `useRenderElement`: call it `ref`, and accept an array optionally.

Comment (atomiks) [reply packages/react/src/composite/item/CompositeItem.tsx:20]: Since it's a component, it doesn't work properly (especially in React <19)

**Review by mj12albert — APPROVED** [review]
Works 👍 
Tested with toggle and toggle group using the original repro: https://codesandbox.io/p/sandbox/pedantic-silence-6qgh9t

File: packages/react/src/composite/root/CompositeRoot.tsx (hunk 1 above)
Comment (atomiks) [reply packages/react/src/composite/root/CompositeRoot.tsx:24]: They're spread inside the array, so it will always use `useForkRefN` regardless
