### PR TITLE
[useScrollLock] Simplify behavior when `scrollbar-gutter` is supported

### LINKED ISSUE #3180: Menu has wrong position after document height changes
# Bug report

## Current behavior

Steps to reproduce:

1. On macOS, make sure scroll bar behaviour is set to "Always"
1. In the [reduced test case](https://codesandbox.io/p/devbox/zen-sky-fpcd7k?file=%2Fsrc%2FApp.tsx&workspaceId=ws_4qKVDKGuRrrvd8oLfoRWSz), scroll down, open the menu, then click the menu item.

Behaviour: the menu is repositioned to the bottom of the screen.

https://github.com/user-attachments/assets/48392727-33c1-4e88-a698-2d797fc4a0ae

## Expected behavior

The menu should remain anchored to the trigger.

## Reproducible example

https://codesandbox.io/p/devbox/zen-sky-fpcd7k?file=%2Fsrc%2FApp.tsx&workspaceId=ws_4qKVDKGuRrrvd8oLfoRWSz

## Base UI version

1.0.0-beta.4

## Which browser are you using?

Chrome

## Which OS are you using?

Mac OS

## Which assistive tech are you using (if applicable)?

N/A

## Additional context

N/A

### PR DESCRIPTION
**Pull request by atomiks**
- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/base-ui/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).

Fixes #3180
Fixes https://github.com/mui/base-ui/issues/2126 (https://codesandbox.io/p/sandbox/kind-tu-yp2qtf)
Fixes https://github.com/mui/base-ui/issues/3189
Closes https://github.com/mui/base-ui/issues/2598 (simplified signature for `/utils` package which people can use)

This removes the special `height` handling set on the body which breaks custom scroll updates. Only old Safari is likely to be an issue here (before 18.2) which is why I've kept the old logic still. We can probably remove the logic entirely in a year or so when Safari 27 is released, given a "last two-three versions" support guide

## Breaking change

The `useScrollLock` utility signature was simplified to `useScrollLock(enabled: boolean, referenceElement?: Element | null)`

### CODE REVIEW

File: packages/react/src/utils/useScrollLock.ts [hunk 1]
```diff
@@ -98,47 +98,58 @@ function preventScrollStandard(referenceElement: Element | null) {
...
-      overflow: 'hidden',
-      scrollBehavior: 'unset',
-    });
-
-    body.scrollTop = scrollTop;
-    body.scrollLeft = scrollLeft;
-    html.setAttribute('data-base-ui-scroll-locked', '');
-    html.style.scrollBehavior = 'unset';
+    if (supportsStableScrollbarGutter) {
+      html.style.scrollbarGutter = 'stable';
```
Comment (mj12albert) [inline packages/react/src/utils/useScrollLock.ts]: https://github.com/mui/base-ui/issues/3189

Perhaps this is an easy fix to include since computed styles are already available here

File: packages/react/src/utils/useScrollLock.ts [hunk 2]
```diff
@@ -219,31 +234,9 @@ const SCROLL_LOCKER = new ScrollLocker();
...
-export function useScrollLock(params: {
-  enabled: boolean;
-  mounted: boolean;
-  open: boolean;
-  referenceElement?: Element | null;
-}) {
-  const { enabled = true, mounted, open, referenceElement = null } = params;
-
-  // https://github.com/mui/base-ui/issues/1135
-  useIsoLayoutEffect(() => {
```
Comment (atomiks) [inline packages/react/src/utils/useScrollLock.ts:232]: This hook was no longer executing after we changed `enabled` to be `false` immediately on close (without waiting for exit animations). And the bug it was fixing isn't present now due to that, so it can be removed with the `useScrollLock` signature simplified. That also solves: https://github.com/mui/base-ui/issues/2598
