### PR TITLE
[combobox][select] Fix `onValueChange` type inference when `value` is unspecified

### LINKED ISSUE #2891: [combobox][typescript] onValueChange value is nullable
# Bug report

## Current behavior

`value` is not correctly typed as `| null`

## Expected behavior

Since `value` is nullable, it should be expressed as such in Typescript

## Base UI version

1.0.0-beta.4

### PR DESCRIPTION
**Pull request by atomiks**
- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/base-ui/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).

This includes `| null` in the `onValueChange` type if `value` isn't specified as a prop. If `value` is specified it adheres to the generic used.

Fixes #2891 

- Autocomplete: inference comes from `items`: the `Autocomplete.Item` `value` must reference the same shape of an individual item for the inference to be correct in `itemToStringValue`.
- Combobox: inference comes from `value`/`defaultValue`, like Select: the `Combobox.Item` `value` must reference the same shape as the root props for inference to be correct in `itemToStringValue`/`itemToStringLabel`. It's not possible(?) to fallback to `items` for inference in case one of those is missing, so explicit typing is required.

Also cleans up JSDoc types and wrapping logic + renamed `ComboboxRootInternal` to `AriaCombobox` (that is, `role=combobox`) for `Autocomplete` wrapping to be less confusing

### CODE REVIEW

File: packages/react/src/select/root/SelectRoot.tsx [hunk 1]
```diff
@@ -17,6 +17,12 @@ import { stringifyAsValue } from '../../utils/resolveValueLabel';
  *
  * Documentation: [Base UI Select](https://base-ui.com/react/components/select)
  */
+export function SelectRoot<Value, Multiple extends boolean | undefined = false>(
+  props: SelectRootControlledProps<Value, Multiple>,
+): React.JSX.Element;
+export function SelectRoot<Value, Multiple extends boolean | undefined = false>(
+  props: SelectRootUncontrolledProps<Value, Multiple>,
+): React.JSX.Element;
```
Comment (atomiks) [inline packages/react/src/select/root/SelectRoot.tsx:25]: Wrappers also would need to create overloads to have correct inference for the consumers, but these types seem overly complex to specify on the namespace. Maybe they need to just recreate them locally.

File: packages/react/src/autocomplete/root/AutocompleteRoot.tsx [hunk 2]
```diff
@@ -70,30 +79,29 @@ export function AutocompleteRoot<Value>(props: AutocompleteRoot.Props<Value>): R
...
 
-  // In "both", wrap filtering to use only the typed value, ignoring overlay.
-  let effectiveFilter: typeof other.filter;
-  if (mode !== 'both') {
-    effectiveFilter = staticItems ? null : other.filter;
-  } else {
-    effectiveFilter = (item: any, _query: string, toString?: (item: any) => string) => {
-      return baseFilter(item, query, toString);
+  // In "both", wrap filtering to use only the typed value, ignoring the inline value.
+  const resolvedFilter: typeof other.filter = React.useMemo(() => {
```
Comment (LukasTy) [inline packages/react/src/autocomplete/root/AutocompleteRoot.tsx:94]: Is `React.memo` worth it here, given that `resolvedQuery` will force its recalculation very often? 🤔

File: packages/react/src/combobox/root/AriaCombobox.tsx [hunk 3]
```diff
@@ -1270,17 +1271,16 @@ interface ComboboxRootProps<ItemValue> {
...
    * Filter function used to match items vs input query.
-   * The `itemToStringLabel` function is provided to help convert items to strings for comparison.
    */
   filter?:
     | null
     | ((
         itemValue: ItemValue,
         query: string,
-        itemToStringLabel?: (itemValue: ItemValue) => string,
+        itemToString?: (itemValue: ItemValue) => string,
```
Comment (LukasTy) [inline packages/react/src/combobox/root/AriaCombobox.tsx:1277]: Isn't this name change a BC? 🤔

File: packages/react/src/combobox/root/ComboboxRoot.spec.tsx [hunk 4]
```diff
@@ -13,10 +13,54 @@ const objectItemsReadonly = [
...
+    return item.label;
+  }}
+/>;
+
 <Combobox.Root
   items={objectItems}
   defaultValue="a"
   onValueChange={(value) => {
+    // @ts-expect-error
     value.startsWith('a');
```
Comment (LukasTy) [inline packages/react/src/combobox/root/ComboboxRoot.spec.tsx]: Maybe we could maintain the previous check? 🤔 
```suggestion
    // @ts-expect-error - possibly null
    value.startsWith('a');
    value?.startsWith('a');
```

File: packages/react/src/combobox/root/ComboboxRoot.spec.tsx [hunk 5]
```diff
@@ -25,6 +69,7 @@ const objectItemsReadonly = [
   items={objectItemsReadonly}
   defaultValue="a"
   onValueChange={(value) => {
+    // @ts-expect-error
     value.startsWith('a');
```
Comment (LukasTy) [inline packages/react/src/combobox/root/ComboboxRoot.spec.tsx]:
```suggestion
    // @ts-expect-error - possibly null
    value.startsWith('a');
    value?.startsWith('a');
```

File: packages/react/src/select/root/SelectRoot.tsx (hunk 1 above)
Comment (LukasTy) [reply packages/react/src/select/root/SelectRoot.tsx:25]: This is a slight inconvenience. 🙈 
Have you considered alternatives where it wouldn't require consumer intervention? 🤔 
As it stands, we are complicating the code as well as usage only for TS correctness in one case .

**Review by LukasTy — COMMENTED** [review]
Very nice improvements, nice work. 👍 
However, I have some reservations about the approach and the resulting types/docs. 🤔

File: packages/react/src/combobox/root/AriaCombobox.tsx (hunk 3 above)
Comment (atomiks) [reply packages/react/src/combobox/root/AriaCombobox.tsx:1277]: Nope, it's just the parameter name that shows up in types. It was confusing because Autocomplete doesn't have this same prop name

File: packages/react/src/autocomplete/root/AutocompleteRoot.tsx (hunk 2 above)
Comment (atomiks) [reply packages/react/src/autocomplete/root/AutocompleteRoot.tsx:94]: Probably depends on the overall component logic outside, but I think it's worth it here overall to reduce additional subscription re-renders. Root hook calls are less expensive than item ones

File: packages/react/src/select/root/SelectRoot.tsx (hunk 1 above)
Comment (atomiks) [reply packages/react/src/select/root/SelectRoot.tsx:25]: To be fair, Combobox has the same overloads already. The overloads seemed necessary to make the type inference work correctly in all the `spec` cases I made, maybe a skill issue on my behalf, or TS limitations. It's a tricky topic 🤔

File: packages/react/src/combobox/root/AriaCombobox.tsx [hunk 6]
```diff
@@ -1270,17 +1271,16 @@ interface ComboboxRootProps<ItemValue> {
    * The items to be displayed in the list.
    * Can be either a flat array of items or an array of groups with items.
    */
-  items?: readonly ItemValue[] | readonly Group<ItemValue>[];
+  items?: readonly any[] | readonly Group<any>[];
```
Comment (LukasTy) [inline packages/react/src/combobox/root/AriaCombobox.tsx:1268]: Could `any` be avoided here? 🤔 
In general, I feel like the current `"ItemValue[] | Group<ItemValue>[] | undefined"` in docs types is slightly more clear than the suggested `"any[] | Group[] | undefined"`. 🙈

Comment (atomiks) [reply packages/react/src/combobox/root/AriaCombobox.tsx:1268]: `ItemValue` is misleading for `Combobox` since it might not represent the item value. `any[]` is more accurate here

File: packages/react/src/combobox/root/AriaCombobox.tsx (hunk 3 above)
Comment (LukasTy) [reply packages/react/src/combobox/root/AriaCombobox.tsx:1277]: Oh, I missed that it's not an object parameter. 👌 
As for the name, it looks like it is the same for both `Combobox` and `Autocomplete` on master. 🤔

File: docs/src/app/(public)/(content)/react/components/autocomplete/page.mdx [hunk 7]
```diff
@@ -64,6 +64,10 @@ import { Autocomplete } from '@base-ui-components/react/autocomplete';
   parts="Input, Trigger, Icon, Clear, List, Portal, Backdrop, Positioner, Popup, Arrow, Status, Empty, Collection, Row, Item, Group, GroupLabel, Separator"
 />
 
+## TypeScript inference
+
+Autocomplete infers the item type from the `items` prop passed to `Autocomplete.Root`. If using `itemToStringLabel`, `Autocomplete.Item`'s `value` prop must match the type of an item in the `items` array.
```
Comment (LukasTy) [inline docs/src/app/(public)/(content)/react/components/autocomplete/page.mdx]:
```suggestion
Autocomplete infers the item type from the `items` prop passed to `<Autocomplete.Root>`.
If using `itemToStringLabel`, `<Autocomplete.Item>`'s `value` prop must match the type of an item in the `items` array.
```

File: docs/src/app/(public)/(content)/react/components/combobox/page.mdx [hunk 8]
```diff
@@ -117,6 +117,10 @@ Accepts all `Intl.CollatorOptions`, plus the following options:
   }}
 />
 
+## TypeScript inference
+
+Combobox infers the item type from the `defaultValue` or `value` props passed to `Combobox.Root`. When using `itemToStringLabel` or `itemToStringValue`, `Combobox.Item`'s `value` prop must match the type passed to `defaultValue` or `value`. When not specifying value props, the parameter's type must be explicitly specified.
```
Comment (LukasTy) [inline docs/src/app/(public)/(content)/react/components/combobox/page.mdx:122]:
```suggestion
Combobox infers the item type from the `defaultValue` or `value` props passed to `<Combobox.Root>`.
When using `itemToStringLabel` or `itemToStringValue`, `<Combobox.Item>`'s `value` prop must match the type passed to `defaultValue` or `value`.
When value props are not specified, the parameter's type must be explicitly specified.
```

File: packages/react/src/autocomplete/root/AutocompleteRoot.tsx (hunk 2 above)
Comment (LukasTy) [reply packages/react/src/autocomplete/root/AutocompleteRoot.tsx:94]: I've added a console.log in this memo and tried searching/using Autocomplete examples.
It looks like basically every keystroke results in rerunning this memo.
Given Rom's position, he would push towards replacing this with a simple function if it reads nicer with one, because such inefficient memos are worse for performance. 🤔

File: packages/react/src/combobox/root/AriaCombobox.tsx (hunk 6 above)
Comment (LukasTy) [reply packages/react/src/combobox/root/AriaCombobox.tsx:1268]: Ok, makes sense.
But maybe the docs could resolve it more precisely?
Not the `<any>` is excluded from the docs. 🙈

File: packages/react/src/select/root/SelectRoot.tsx (hunk 1 above)
Comment (LukasTy) [reply packages/react/src/select/root/SelectRoot.tsx:25]: Ok.
Then maybe it could make sense to add documentation about this fact if majority of our users are going to wrap these components? 🤔

File: docs/src/app/(public)/(content)/react/components/autocomplete/page.mdx (hunk 7 above)
Comment (atomiks) [reply docs/src/app/(public)/(content)/react/components/autocomplete/page.mdx]: I agree this is better, but I think we should do a mass-update in a different PR as most of our pages aren't using this format yet

File: packages/react/src/combobox/root/AriaCombobox.tsx (hunk 3 above)
Comment (atomiks) [reply packages/react/src/combobox/root/AriaCombobox.tsx:1277]: Since it's reused across both, it has to be less descriptive so it can suit both components

File: packages/react/src/combobox/root/AriaCombobox.tsx (hunk 6 above)
Comment (atomiks) [reply packages/react/src/combobox/root/AriaCombobox.tsx:1268]: That's an issue for the API docs generator, not much we can do here atm

File: packages/react/src/autocomplete/root/AutocompleteRoot.tsx (hunk 2 above)
Comment (atomiks) [reply packages/react/src/autocomplete/root/AutocompleteRoot.tsx:94]: I was more so thinking about how often the parent re-renders `Autocomplete.Root` since in that case it also passes an unmemoized function down. For keystrokes it doesn't matter yeah. I feel like the `filter` function should always be memoized where possible; I think this one is low-impact

File: packages/react/src/select/root/SelectRoot.tsx (hunk 1 above)
Comment (atomiks) [reply packages/react/src/select/root/SelectRoot.tsx:25]: Yes, possibly. A few of our other components do this, so I think it's probably something better for a new PR. Maybe our TypeScript page needs an update.

File: docs/src/app/(public)/(content)/react/components/autocomplete/page.mdx (hunk 7 above)
Comment (LukasTy) [reply docs/src/app/(public)/(content)/react/components/autocomplete/page.mdx]: Sure, makes sense. 👌

File: packages/react/src/autocomplete/root/AutocompleteRoot.tsx (hunk 2 above)
Comment (LukasTy) [reply packages/react/src/autocomplete/root/AutocompleteRoot.tsx:94]: Oh, gotcha. 👌 
We can keep the memo to improve that case. 👍

**Review by LukasTy — APPROVED** [review]
LGTM. 👍 
Some improvements can be done as follow-ups and are not directly related to this PR. 👌

File: packages/react/src/select/root/SelectRoot.tsx (hunk 1 above)
Comment (songkeys) [reply packages/react/src/select/root/SelectRoot.tsx:25]: I bumped my head into this while upgrading from beta.4 to beta.5. This pr is not in the breaking changes. And no docs about this. Might be confusing?

SCR-20251118-gngv

Comment (atomiks) [reply packages/react/src/select/root/SelectRoot.tsx:25]: @songkeys yeah definitely, it's unfortunately a complex problem (from what I see) - I opened #3252

Comment (atomiks) [reply packages/react/src/select/root/SelectRoot.tsx:25]: Update: we may remove the overloads to simplify this use case, with a small inconvenience for controlled values: https://github.com/mui/base-ui/pull/3254
