### PR TITLE
[menu] Fix `closeParentOnEsc` default value

### LINKED ISSUE #2490: [menu] Focus is lost when `closeParentOnEsc: false`
# Bug report

## Current behavior

Currently, when `closeParentOnEsc: false` is set on Menu.Submenu, pressing the ESC key causes the Submenu to disappear and the focus to be lost as well.

https://github.com/user-attachments/assets/49c7d86f-e4b5-439a-baf8-f7f10c5bfa90

## Expected behavior

According to the [MDN documentation](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Reference/Roles/menu_role#escape), when the focus is on a submenu, pressing the ESC key should close the submenu and move focus to the submenu trigger.

## Reproducible example

https://codesandbox.io/p/sandbox/silent-sound-x4fghr?file=%2Fsrc%2FApp.tsx%3A23%2C37

## Base UI version

v1.0.0-beta.2

## Which browser are you using?

Chrome

## Which OS are you using?

Mac OS

## Which assistive tech are you using (if applicable)?

X

### PR DESCRIPTION
**Pull request by seongminn**
- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/base-ui/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).

closed #2490

According to the [MDN documentation](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Reference/Roles/menu_role#escape), when the focus is on a submenu, pressing the ESC key should close the submenu and move focus to the submenu trigger.

Additionally, the [Base UI documentation](https://master--base-ui.netlify.app/react/components/menu#MenuPopup-finalFocus) states that when the Esc key is pressed, the focus should return to the trigger element by default.

However, the current implementation has two issues:

- When Esc is pressed in a submenu, the entire menu closes.
- When `closeParentOnEsc` is set to `false`, the root menu remains open, but the focus is lost completely.

To resolve this, the following changes have been implemented:

- The default value of closeParentOnEsc in Menu.SubmenuRoot is now `false`.
- When the Esc key is pressed in a Submenu, the Submenu will close, and the focus will correctly move to the SubmenuTrigger.

### CODE REVIEW

File: packages/react/src/menu/popup/MenuPopup.tsx [hunk 1]
```diff
@@ -107,7 +110,7 @@ export const MenuPopup = React.forwardRef(function MenuPopup(
       context={floatingContext}
       modal={false}
       disabled={!mounted}
-      returnFocus={finalFocus || returnFocus}
+      returnFocus={finalTriggerElement || returnFocus}
```
Comment (atomiks) [inline packages/react/src/menu/popup/MenuPopup.tsx]: This prevents `returnFocus` from ever being passed, no?

It seems like `finalTriggerElement` needs to be part of the if branches above when calculating `returnFocus`

File: packages/react/src/menu/submenu-root/MenuSubmenuRoot.tsx [hunk 2]
```diff
@@ -12,9 +12,11 @@ export { useMenuSubmenuRootContext } from './MenuSubmenuRootContext';
  * Documentation: [Base UI Menu](https://base-ui.com/react/components/menu)
  */
 export function MenuSubmenuRoot(props: MenuSubmenuRoot.Props) {
+  const { closeParentOnEsc = false } = props;
+
   return (
     <MenuSubmenuRootContext.Provider value>
-      <MenuRoot {...props} />
+      <MenuRoot closeParentOnEsc={closeParentOnEsc} {...props} />
```
Comment (atomiks) [inline packages/react/src/menu/submenu-root/MenuSubmenuRoot.tsx:19]: macOS closes them all simultaneously; not sure if this should change as a default

Comment (seongminn) [reply packages/react/src/menu/submenu-root/MenuSubmenuRoot.tsx:19]: According to the [MDN documentation](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Reference/Roles/menu_role#escape), pressing ESC in a submenu should return focus to the parent menu or menuitem.
I've implemented this as the default behavior for submenus based on that recommendation.

I'm curious to hear your thoughts on this.

File: packages/react/src/menu/popup/MenuPopup.tsx (hunk 1 above)
Comment (seongminn) [reply packages/react/src/menu/popup/MenuPopup.tsx]: Included in this [commit](https://github.com/mui/base-ui/pull/2493/commits/2509ccf26579f268029d5538c20469560db085a5).

File: packages/react/src/menu/submenu-root/MenuSubmenuRoot.tsx (hunk 2 above)
Comment (atomiks) [reply packages/react/src/menu/submenu-root/MenuSubmenuRoot.tsx:19]: I'm not too fussed either way, and am ok with changing it if this default is better suited in the web paradigm cc: @colmtuite

File: packages/react/src/menu/popup/MenuPopup.tsx (hunk 1 above)
Comment (atomiks) [reply packages/react/src/menu/popup/MenuPopup.tsx]: Seems good now - also tested Menubar and the return focus issue this branch was addressing is still not present
