### PR TITLE
[navigation menu] Support inlined nesting

### LINKED ISSUE #2253: [navigation menu] Support inlined nesting
# Bug report

### 1. `--popup-height` is not updated on content change

When the content inside `NavigationMenu.Content` changes (e.g. dynamically loaded or conditionally rendered), the `--popup-height` variable is not updated to reflect the new height. As a result, if you're animating the popup height using this variable, the transition breaks — the height appears stuck at its previous value (`auto`), and no animation occurs. The only way to update it is by activating another trigger, which forces a re-evaluation, but nothing listens to content size changes dynamically.

### 2. No transition on nested NavigationMenu

When nesting another `NavigationMenu` inside a parent item (e.g. for multi-level navigation), and using a `defaultValue` to preselect a nested item, the transition effect is skipped entirely. It seems like the inner `NavigationMenu.Viewport` is delayed in rendering or measuring, and that causes the quick jump instead of a smooth transition.

### 3. No direction-based transitions when skipping `Positioner`/`Popover`

Migrating from Radix UI's `NavigationMenu`, we had the ability to render the `Viewport` without a `Portal`, `Positioner`, or `Popover`. This was useful for building custom layouts like nested menus without extra wrappers.

With Base UI's current setup, skipping `Positioner` or `Popover` breaks direction-based transitions. The `Content` seems unaware of the "activation direction" (`left | right | top | bottom`), so the enter animation doesn't apply. It seems necessary to wrap everything again inside `Positioner`/`Popover`, even if it's not needed visually, just to get the state propagation working.

## Expected behavior

- The `--popup-height` CSS variable should update reactively when content height changes, enabling smooth transitions.
- Nested `NavigationMenu` transitions should respect the correct enter/exit animations when `defaultValue` is set.
- `NavigationMenu.Content` should still be able to determine the activation direction and animate correctly even if `Popover`/`Positioner` are not used, to support more flexible layout use cases.

## Reproducible example

https://stackblitz.com/edit/vitejs-vite-4erpxnu7?file=src%2FApp.tsx

## Base UI version

1.0.0-beta.1

## Which browser are you using?

Chrome (latest version)

## Which OS are you using?

macOS

## Which assistive tech are you using (if applicable)?

N/A

## Additional context

https://github.com/user-attachments/assets/47e13de8-7367-4536-bf4c-8f4fe1729c62

https://github.com/user-attachments/assets/17918dc4-acab-43d0-a1c2-7faf0aecd5b2

### PR DESCRIPTION
**Pull request by atomiks**
- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/base-ui/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).

Closes #2253

https://deploy-preview-2269--base-ui.netlify.app/experiments/navigation-menu

In the experiment, the content doesn't have any transitions of its own (except for Collapsible) - what this is testing is the ability for the popup to transition its size when content is inserted, along with the ability for content to drive the transition itself instead of the Popup (Collapsible). This PR also fixes the `Positioner` dimensions not being updated (which doesn't end up affecting `height` changes, but does affect `width` changes)

For inlined content, the inline viewport never gets unmounted like with popups

### CODE REVIEW

File: packages/react/src/navigation-menu/utils/setFixedSize.ts [hunk 1]
```diff
@@ -0,0 +1,17 @@
+import { NavigationMenuPopupCssVars } from '../popup/NavigationMenuPopupCssVars';
+import { NavigationMenuPositionerCssVars } from '../positioner/NavigationMenuPositionerCssVars';
+
+export function setFixedSize(element: HTMLElement, type: 'popup' | 'positioner') {
+  element.style.setProperty(
+    type === 'popup'
+      ? NavigationMenuPopupCssVars.popupWidth
+      : NavigationMenuPositionerCssVars.positionerWidth,
+    `${element.offsetWidth}px`,
```
Comment (michaldudak) [inline packages/react/src/navigation-menu/utils/setFixedSize.ts]: `offsetWidth` returns a rounded value. I ran into this issue in the detached popovers POC, where a fraction of a pixel of difference caused the text to be broken into lines differently. `getBoundingClientRect` returns exact values.

Image

File: packages/react/src/navigation-menu/trigger/NavigationMenuTrigger.tsx [hunk 2]
```diff
@@ -91,10 +95,32 @@ export const NavigationMenuTrigger = React.forwardRef(function NavigationMenuTri
...
+  const allowFocusRef = React.useRef(false);
+  const prevSizeRef = React.useRef({ width: 0, height: 0 });
+  const abortControllerRef = React.useRef(new AbortController());
+
   const isActiveItem = open && value === itemValue;
   const isActiveItemRef = useLatestRef(isActiveItem);
+  const interactionsEnabled = positionerElement ? true : !value;
 
-  const allowFocusRef = React.useRef(false);
+  const runOnceAnimationsFinish = useAnimationsFinished({ current: popupElement });
```
Comment (michaldudak) [inline packages/react/src/navigation-menu/trigger/NavigationMenuTrigger.tsx]: It's better to update `useAnimationsFinished` to accept an element than to instantiate a new object on each render (see https://github.com/mui/base-ui/pull/2336/files#diff-391ac91919dc0519485d440c415899b7c7c95296b05a5161487094a82151a60e)

File: packages/react/src/navigation-menu/trigger/NavigationMenuTrigger.tsx [hunk 3]
```diff
@@ -91,10 +95,32 @@ export const NavigationMenuTrigger = React.forwardRef(function NavigationMenuTri
   const [stickIfOpen, setStickIfOpen] = React.useState(true);
   const [pointerType, setPointerType] = React.useState<'mouse' | 'touch' | 'pen' | ''>('');
 
+  const allowFocusRef = React.useRef(false);
+  const prevSizeRef = React.useRef({ width: 0, height: 0 });
+  const abortControllerRef = React.useRef(new AbortController());
```
Comment (romgrk) [inline packages/react/src/navigation-menu/trigger/NavigationMenuTrigger.tsx]: It would be nice to put a bit more care into avoiding useless allocations. The size ref could have the empty/default state extracted to a static variable, and the abort controller ref could use `useLazyRef` to build only one `AbortController`.

Comment (romgrk) [reply packages/react/src/navigation-menu/trigger/NavigationMenuTrigger.tsx]: lint: The abort controller ref could be named for what it aborts, it would make it easier to understand what it does, e.g. `animationsController`.

Comment (romgrk) [reply packages/react/src/navigation-menu/trigger/NavigationMenuTrigger.tsx]: You could also build the abort controller lazily (when it's first needed) and leave the ref empty, that would be more efficient.

File: packages/react/src/navigation-menu/utils/setFixedSize.ts (hunk 1 above)
Comment (atomiks) [reply packages/react/src/navigation-menu/utils/setFixedSize.ts]: This can break scaling animations on the popup. In the CSS I've used `width: max-content` to avoid the line breaking bug.

Comment (atomiks) [reply packages/react/src/navigation-menu/utils/setFixedSize.ts]: Floating UI uses CSS dimensions which avoids being affected by `transform: scale` while also returning fractional values. I guess we could use this: https://github.com/floating-ui/floating-ui/blob/master/packages/dom/src/utils/getCssDimensions.ts

File: packages/react/src/navigation-menu/trigger/NavigationMenuTrigger.tsx [hunk 4]
```diff
@@ -129,76 +157,64 @@ export const NavigationMenuTrigger = React.forwardRef(function NavigationMenuTri
...
 
-  const setAutoSizes = useEventCallback(() => {
-    if (!popupElement) {
-      return;
+  React.useEffect(() => {
+    if (!open) {
+      stickIfOpenTimeout.clear();
+      sizeFrame1.cancel();
+      sizeFrame2.cancel();
+      prevSizeRef.current = { width: 0, height: 0 };
```
Comment (romgrk) [inline packages/react/src/navigation-menu/trigger/NavigationMenuTrigger.tsx]: This should use the newly extracted default state variable.

File: packages/react/src/utils/useAnimationsFinished.ts [hunk 5]
```diff
@@ -6,11 +6,11 @@ import { useEventCallback } from '@base-ui-components/utils/useEventCallback';
 
 /**
  * Executes a function once all animations have finished on the provided element.
- * @param ref - The element to watch for animations.
+ * @param elementOrRef - The element to watch for animations.
  * @param waitForNextTick - Whether to wait for the next tick before checking for animations.
  */
 export function useAnimationsFinished(
-  ref: React.RefObject<HTMLElement | null>,
+  elementOrRef: React.RefObject<HTMLElement | null> | HTMLElement | null,
```
Comment (romgrk) [inline packages/react/src/utils/useAnimationsFinished.ts:13]: Why does this function need to accept a ref in the first place? All it needs is an `HTMLElement`. Rather than add runtime detection of the type here, the caller should pass the element.

File: packages/react/src/navigation-menu/trigger/NavigationMenuTrigger.tsx [hunk 6]
```diff
@@ -91,10 +97,32 @@ export const NavigationMenuTrigger = React.forwardRef(function NavigationMenuTri
...
-  const allowFocusRef = React.useRef(false);
+  const runOnceAnimationsFinish = useAnimationsFinished(popupElement);
+
+  if (!open && pointerType !== '') {
+    setPointerType('');
+  }
+
+  React.useEffect(() => {
+    abortControllerRef.current.abort();
+  }, [isActiveItem]);
```
Comment (romgrk) [inline packages/react/src/navigation-menu/trigger/NavigationMenuTrigger.tsx]: To give you an example regarding the naming of this variable, while reviewing this PR I had no idea what this effect was about until I found where `abortControllerRef` was used below. Ideally the naming should make it clear what it's used for, without having to look for what the code does. Bonus point if you move the variable declaration next to the `useAnimationsFinished` hook - variables that are used together should be declared together.

File: packages/react/src/utils/useAnimationsFinished.ts (hunk 5 above)
Comment (atomiks) [reply packages/react/src/utils/useAnimationsFinished.ts:13]: The element isn't always available, it can be a ref.
But I think it might be better if it's just a function called `getElement` so you can return either one without issues. @michaldudak

Comment (romgrk) [reply packages/react/src/utils/useAnimationsFinished.ts:13]: Ah right, nevermind then, I don't think allocating a new function for this is good.

File: packages/react/src/navigation-menu/trigger/NavigationMenuTrigger.tsx [hunk 7]
```diff
@@ -129,76 +157,64 @@ export const NavigationMenuTrigger = React.forwardRef(function NavigationMenuTri
...
-      sizeFrame2.request(() => {
-        runOnceAnimationsFinish(setAutoSizes, ac.signal);
-      });
+    const mutationObserver = new MutationObserver(() => {
+      if (!popupElement) {
+        return;
+      }
+
+      abortControllerRef.current.abort();
+      abortControllerRef.current = new AbortController();
```
Comment (romgrk) [inline packages/react/src/navigation-menu/trigger/NavigationMenuTrigger.tsx]: This works, but it seems more intuitive to me to create a new `AbortController` when a new one is needed - when `runOnceAnimationsFinish` is called.

File: packages/react/src/navigation-menu/trigger/NavigationMenuTrigger.tsx [hunk 8]
```diff
@@ -129,76 +157,64 @@ export const NavigationMenuTrigger = React.forwardRef(function NavigationMenuTri
...
 
-    const ac = new AbortController();
-    sizeFrame1.request(() => {
-      sizeFrame2.request(() => {
-        runOnceAnimationsFinish(setAutoSizes, ac.signal);
-      });
+    const mutationObserver = new MutationObserver(() => {
+      if (!popupElement) {
+        return;
+      }
```
Comment (romgrk) [inline packages/react/src/navigation-menu/trigger/NavigationMenuTrigger.tsx]: Isn't this condition already guarded for by the `if` block just above?

File: packages/react/src/utils/useAnimationsFinished.ts (hunk 5 above)
Comment (atomiks) [reply packages/react/src/utils/useAnimationsFinished.ts:13]: > I don't think allocating a new function for this is good.

Isn't this super common in React components though? Like _every_ hook allocates a new function on every render? I'm curious why it's a perf issue here

Comment (romgrk) [reply packages/react/src/utils/useAnimationsFinished.ts:13]: Yes, super common, which is why I try to avoid allocations as much as possible. Most of the big perf improvements I did on material-ui that got us 30-50% boost were just removing small memory allocations all over the place. People don't realize the impact of allocations. Ofc there's only so much you can do in the React world, but I've been slowly introducing hooks that avoid allocations. For example, `useOnMount` can skip the empty `[]` dependency, or `useLazyRef` can use an initialization function. This can be used to create hooks or components that don't allocate anything in the render phase - [useTimeout is a good example of that](https://github.com/mui/base-ui/blob/8dda8cd7456e071a3dbad2a3ae7aabc91c06e745/packages/utils/src/useTimeout.ts#L46-L52) - and I plan to expand that pattern to all the "hot path" components.

Imo, the lack of a "constructor" phase in functional components is a mistake that pushes devs into allocating too much stuff because they don't have an easy/recommended way to do otherwise. If you look at React's implementation of hooks, they even have separate implementation of hooks for ["mount"](https://github.com/facebook/react/blob/19baee813cb08fc5971a3b301814faa6cd530ec8/packages/react-reconciler/src/ReactFiberHooks.js#L3875) and ["rerender"](https://github.com/facebook/react/blob/19baee813cb08fc5971a3b301814faa6cd530ec8/packages/react-reconciler/src/ReactFiberHooks.js#L3935), so they recognize the need for an initialization phase, they just keep it for themselves :|

tldr: allocations create a "death by a thousand papercuts" situation

Comment (romgrk) [reply packages/react/src/utils/useAnimationsFinished.ts:13]: > Like every hook allocates a new function on every render? I'm curious why it's a perf issue here

So essentially you're asking why we can't add this papercut considering we already have tons of them. The other papercuts (inline hook closures), we could avoid but it would require a coding style that's foreign to react, and I don't think I can suggest that change without opposition from nearly everyone in the team. This papercut though, we have the option to avoid it. That's why I'm suggesting to avoid this one.

File: packages/react/src/navigation-menu/utils/setFixedSize.ts (hunk 1 above)
Comment (romgrk) [reply packages/react/src/navigation-menu/utils/setFixedSize.ts]: Fyi, `getBoundingClientRect` returns the exact dimensions filled by pixels post-rendering, but it can be affected by rendering artifacts (e.g. anti-aliasing and all the fun stuff related to graphics programming), so in some cases its value can slightly mismatch CSS dimensions. CSS dimensions (`getComputedStyle`) are the logical values that are used by the browser's layout engine, pre-rendering.

**Comment by michaldudak** [comment]
The popup can't decide which side it wants to stay on (tested on Edge and Safari on macOS):

https://github.com/user-attachments/assets/b9f23c2f-9d7d-420e-a8d4-7eb00e118ca6

File: packages/react/src/navigation-menu/viewport/NavigationMenuViewport.tsx [hunk 9]
```diff
@@ -14,16 +70,61 @@ export const NavigationMenuViewport = React.forwardRef(function NavigationMenuVi
...
+    }
+  }, [domReference, prevTriggerElementRef]);
 
   const element = useRenderElement('div', componentProps, {
     ref: [forwardedRef, setViewportElement],
-    props: elementProps,
+    props: [
+      {
+        id,
+        onBlur(event) {
```
Comment (romgrk) [inline packages/react/src/navigation-menu/viewport/NavigationMenuViewport.tsx:100]: This is another common pattern that creates allocations. We already have an owned "props" variable (`elementProps`), we could set these properties directly on it rather than wrap them in an additional array & object.

Comment (atomiks) [reply packages/react/src/navigation-menu/viewport/NavigationMenuViewport.tsx:100]: That seems excessive, especially given unlike other components navigation menu is really one where there'll only be one or two per page. (They aren't used in data grids)

Plus we would override their event handlers potentially if we set it on `elementProps`.

**Comment by atomiks** [comment]
@michaldudak was caused by the last commit, removed it and changed technique

File: docs/src/app/(public)/(content)/react/components/navigation-menu/demos/hero/css-modules/index.module.css [hunk 10]
```diff
@@ -121,13 +121,9 @@
   transition-property: opacity, transform, width, height;
   transition-duration: var(--duration);
   transition-timing-function: var(--easing);
-  width: max-content;
+  width: var(--popup-width);
   height: var(--popup-height);
 
-  @media (min-width: 500px) {
-    width: var(--popup-width);
-  }
```
Comment (atomiks) [inline docs/src/app/(public)/(content)/react/components/navigation-menu/demos/hero/css-modules/index.module.css:129]: This can be considered a breaking change. On <500px, the popup collapses in size when animating out
