### PR TITLE
[useScrollLock] Fix jump with `scroll-behavior` style

### LINKED ISSUE #1340: [Dialog] Page is scrolled to top when opening the dialog if `html { scroll-behavior: smooth }`
# Bug report

## Current behavior

Super weird one, but like the title says! I can reproduce in Chrome and Safari; it works fine in Firefox.

## Expected behavior

The page should _not_ be scrolled to the top when the dialog opens.

## Reproducible example

https://codesandbox.io/p/sandbox/competent-chandrasekhar-8wcv88

## Base UI version

1.0.0-alpha.5

## Which browser are you using?

Chrome 132.0.6834.84, Safari 18.2

## Which OS are you using?

macOS

## Which assistive tech are you using (if applicable)?

None

## Additional context

Thank you 🙏

### PR DESCRIPTION
**Pull request by atomiks**
Fixes #1340

### CODE REVIEW

File: packages/react/src/utils/useScrollLock.ts [hunk 1]
```diff
@@ -52,6 +53,7 @@ function preventScrollStandard(referenceElement?: Element | null) {
       overflowY: html.style.overflowY,
       overflowX: html.style.overflowX,
     };
+    originalHtmlScrollBehavior = html.style.scrollBehavior;
```
Comment (michaldudak) [inline packages/react/src/utils/useScrollLock.ts:56]: Why isn't it a part of `originalHtmlStyles`?

Comment (atomiks) [reply packages/react/src/utils/useScrollLock.ts:56]: It has to be assigned after the `.scrollTop/Left` assignments

**Review by michaldudak — APPROVED** [review]
