### PR TITLE
[menu] Fix menu not opening when inside context menu trigger

### LINKED ISSUE #2505: [menu] Menu inside context menus trigger breaks it
# Bug report

## Current behavior

When I add a Menu in a context menu trigger, the Menu does not open on click

## Reproducible example

https://codesandbox.io/p/devbox/floral-field-pjydn7?workspaceId=ws_LfkA6oJ6xnhrQhvf2LqDo

## Base UI version

beta-2

## Which browser are you using?

Firefox

## Which OS are you using?

Mac OS

### PR DESCRIPTION
**Pull request by baptisteArno**
- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/base-ui/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).

Fixes #2505

### CODE REVIEW

File: packages/react/src/menu/root/MenuRoot.tsx [hunk 1]
```diff
@@ -103,7 +103,8 @@ export const MenuRoot: React.FC<MenuRoot.Props> = function MenuRoot(props) {
         type: 'menubar',
         context: menubarContext,
       };
-    } else if (contextMenuContext) {
+      // Making sure it's not a Menu nested inside a ContextMenuTrigger. ContextMenu parentContext is always undefined (ContextMenuRoot is instantiated with `<MenuRootContext.Provider value={undefined}>`)
+    } else if (contextMenuContext && !parentContext) {
```
Comment (atomiks) [inline packages/react/src/menu/root/MenuRoot.tsx]: Very small fix 😄
 
nit, so comments don't overflow: 

```suggestion
      // Ensure this is not a Menu nested inside ContextMenu.Trigger. 
      // ContextMenu parentContext is always undefined as ContextMenu.Root is instantiated with
      // <MenuRootContext.Provider value={undefined}>
    } else if (contextMenuContext && !parentContext) {
```

**Comment by atomiks** [comment]
Small lint error in the demo with `'e'` variable
