### PR TITLE
[select] Fix instant close with no set value

### LINKED ISSUE #1125: [Select] Closes instantly when no `value`/`defaultValue` is set

### PR DESCRIPTION
**Pull request by atomiks**
Closes #1125

### CODE REVIEW

File: packages/react/src/select/popup/SelectPopup.tsx [hunk 1]
```diff
@@ -88,6 +90,7 @@ const SelectPopup = React.forwardRef(function SelectPopup(
         modal={false}
         disabled={!mounted}
         visuallyHiddenDismiss={modal ? 'Dismiss popup' : undefined}
+        initialFocus={selectedIndex === null ? popupRef : undefined}
         order={['content', 'reference']}
       >
```
Comment (atomiks) [inline packages/react/src/select/popup/SelectPopup.tsx:95]: Removing `order` also fixes it, which was added with modality changes, but not sure if it's truly necessary here @michaldudak

File: packages/react/src/select/root/SelectRoot.test.tsx [hunk 2]
```diff
@@ -315,10 +315,6 @@ describe('<Select.Root />', () => {
       await user.click(trigger);
       expect(handleOpenChange.callCount).to.equal(1);
       expect(handleOpenChange.args[0][0]).to.equal(true);
-
-      await user.click(trigger);
-      expect(handleOpenChange.callCount).to.equal(2);
-      expect(handleOpenChange.args[1][0]).to.equal(false);
```
Comment (atomiks) [inline packages/react/src/select/root/SelectRoot.test.tsx:321]: I don't think this test is valid, because the trigger doesn't need to be the click target to dismiss it, any outside area works fine

**Comment by mnajdova** [comment]
What exactlly is the issue. I try reproducing it here but I can't: https://codesandbox.io/p/sandbox/laughing-shamir-k8hmn8?file=%2Fsrc%2FApp.tsx%3A11%2C32 (it's version from another random PR package).

File: packages/react/src/select/root/SelectRoot.test.tsx (hunk 2 above)
Comment (atomiks) [reply packages/react/src/select/root/SelectRoot.test.tsx:321]: For touch it does require `outsidePressEvent: 'mousedown'`, which matches `Menu`

**Comment by atomiks** [comment]
@mnajdova the trigger needs to be moved down so `alignItemToTrigger` is activated, with the popup on the top of the trigger

`position: relative, top: 100` inline styles on the trigger reveal it

File: packages/react/src/select/root/SelectRoot.test.tsx (hunk 2 above)
Comment (mnajdova) [reply packages/react/src/select/root/SelectRoot.test.tsx:321]: > I don't think this test is valid, because the trigger doesn't need to be the click target to dismiss it, any outside area works fine

It's not that is not valid, but both clicking the trigger or any outside area should close it. Maybe we can actually test both of these two scenarios.

File: packages/react/src/select/popup/SelectPopup.tsx [hunk 3]
```diff
@@ -88,7 +88,6 @@ const SelectPopup = React.forwardRef(function SelectPopup(
         modal={false}
         disabled={!mounted}
         visuallyHiddenDismiss={modal ? 'Dismiss popup' : undefined}
-        order={['content', 'reference']}
```
Comment (mnajdova) [inline packages/react/src/select/popup/SelectPopup.tsx:91]: 👍

**Review by mnajdova — APPROVED** [review]
Looks good. I would add test cases for both scenarios I mentioned in https://github.com/mui/base-ui/pull/1126/files#r1888154490, just to be safe.

File: packages/react/src/select/root/SelectRoot.test.tsx (hunk 2 above)
Comment (atomiks) [reply packages/react/src/select/root/SelectRoot.test.tsx:321]: This particular test fails due to `pointer-events: none;` style, so you can't click the trigger, only the area above it (which is `inert`, similar to a backdrop being present). The end result is the same though
