### PR TITLE
[toast] Fix `flushSync` dev error when toast is added

### LINKED ISSUE #3442: [Toast] flushSync error in v1.0.0-rc
# Bug report

https://github.com/user-attachments/assets/e070e478-daf2-4b9e-9d1b-89c87ef20688

## Current behavior

When adding an anchored toast using Toast.Positioner with an anchor prop, React throws the following error:

`flushSync was called from inside a lifecycle method. React cannot flush when React is already rendering. Consider moving this call to a scheduler task or micro task.`

The error occurs at Toast.Root inside the toast rendering loop. This happens even when deferring the toastManager.add() call using setTimeout, queueMicrotask, requestAnimationFrame

## Expected behavior

Adding an anchored toast should not trigger a flushSync error.

## Reproducible example

[Link](https://stackblitz.com/edit/psxau6po?file=src%2FApp.tsx,package.json)

## Base UI version

v1.0.0-rc.0

## Which browser are you using?

Chrome

## Which OS are you using?

macOS

### PR DESCRIPTION
**Pull request by atomiks**
- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/base-ui/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).

Fixes #3442. `flushSync` should only be called in observer callbacks to prevent flickers but not inside the layout effect directly.

### CODE REVIEW

File: packages/react/src/toast/root/ToastRoot.tsx [hunk 1]
```diff
@@ -146,7 +146,7 @@ export const ToastRoot = React.forwardRef(function ToastRoot(
     },
   });
 
-  const recalculateHeight = useStableCallback(() => {
+  const recalculateHeight = useStableCallback((flushSync = false) => {
```
Comment (mnajdova) [inline packages/react/src/toast/root/ToastRoot.tsx]: Please add a comment explaining when flashSync should be set to true.
