### PR TITLE
[select] Create new `Select` component

### LINKED ISSUE #7: [Select] Out of range defaultValue causes onChange to fire on mount
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/use-select-default-value-triggers-on-change-h5mmmh?file=/Demo.js

Steps:

1. Create a `Select` component using the `useSelect` hook
2. Provide an `onChange` callback to `useSelect`
3. Provide a `defaultValue` to `useSelect` which doesn't correspond to any of the options' values

### Current behavior 😯

When the component mounts, the `onChange` callback is fired with `null` values for the `event` and `newValue` parameters.

### Expected behavior 🤔

- The `onChange` callback shouldn't fire
- There should be a warning about the value provided to `useSelect` being out of range

### Context 🔦

Refactoring `material-ui` v5 Select to be based on the `useSelect` hook. Hopefully, we can make it so that the refactored version fails gracefully when `value = ""` or `defaultValue = ""` as that was the way to deselect all options in v5.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 13.4.1
  Binaries:
    Node: 18.16.1 - ~/.nvm/versions/node/v18.16.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.16.1/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.1/bin/npm
  Browsers:
    Chrome: 117.0.5938.149
    Edge: Not Found
    Safari: 16.5.1
  npmPackages:
    @emotion/react:  11.11.1 
    @emotion/styled:  11.11.0 
    @mui/base:  5.0.0-beta.17 
    @mui/codemod:  5.14.11 
    @mui/core-downloads-tracker:  5.14.11 
    @mui/docs:  5.14.11 
    @mui/envinfo:  2.0.10 
    @mui/icons-material:  5.14.11 
    @mui/internal-waterfall:  1.0.0 
    @mui/joy:  5.0.0-beta.8 
    @mui/lab:  5.0.0-alpha.146 
    @mui/markdown:  5.0.0 
    @mui/material:  5.14.11 
    @mui/material-next:  6.0.0-alpha.103 
    @mui/private-theming:  5.14.11 
    @mui/styled-engine:  5.14.11 
    @mui/styled-engine-sc:  5.14.11 
    @mui/styles:  5.14.11 
    @mui/system:  5.14.11 
    @mui/types:  7.2.4 
    @mui/utils:  5.14.11 
    @mui/x-charts:  6.0.0-alpha.12 
    @mui/x-data-grid:  6.15.0 
    @mui/x-data-grid-generator:  6.15.0 
    @mui/x-data-grid-premium:  6.15.0 
    @mui/x-data-grid-pro:  6.15.0 
    @mui/x-date-pickers:  6.15.0 
    @mui/x-date-pickers-pro:  6.15.0 
    @mui/x-license-pro:  6.10.2 
    @mui/x-tree-view:  6.0.0-alpha.1 
    @mui/zero-jest:  0.0.1-alpha.0 
    @mui/zero-next-plugin:  0.0.1-alpha.0 
    @mui/zero-runtime:  0.0.1-alpha.0 
    @mui/zero-tag-processor:  0.0.1-alpha.0 
    @mui/zero-vite-plugin:  0.0.1-alpha.0 
    @types/react: ^18.2.23 => 18.2.23 
    react:  18.2.0 
    react-dom:  18.2.0 
    styled-components:  5.3.11 
    typescript: ^5.1.6 => 5.1.6 
```
</details>

### LINKED ISSUE #8: [Select] Select menu can't be closed by clicking away
### Steps to reproduce

Link to live example: https://mui.com/base-ui/react-select/#introduction

Steps:
1. Add `value=""` to the `<Select>` component

Screenshot 2024-02-19 at 13 36 06

### Current behavior

- The Select menu can't be closed by clicking away if its `value` prop doesn't match any option's value
- Selecting an option can close the menu though

### Expected behavior

- The Select menu can be closed by clicking away even if its `value` prop doesn't match any option's value

### Context

_No response_

### Your environment

<details>
"@mui/base": "5.0.0-beta.36"
</details>

**Search keywords**: Select

### LINKED ISSUE #14: [Select][base-ui] Set the onChange's event.target.value
As noted in https://github.com/mui/material-ui/pull/34408#discussion_r976288729, it's worth ensuring that the event object in Unstyled Select's `onChange` method has a target property with a valid `value` property.

### LINKED ISSUE #37: [Select] SSR empty render
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

Steps:

1. Open https://mui.com/base-ui/react-select/#introduction
2. Disable JavaScript to see the initial html render before hydration

### Current behavior 😯

Screenshot 2023-07-23 at 18 27 54

### Expected behavior 🤔

Screenshot 2023-07-23 at 18 25 12

### Context 🔦

This is a regression in behavior from Material UI, e.g. https://mui.com/material-ui/react-select/#basic-select, which we would need to fix for Material UI v6 to depend on Base UI.

I noticed this on the https://github.com/mui/material-ui/tree/master/examples/base-next-app-router-tailwind-ts which feels broken:

https://github.com/mui/material-ui/assets/3165635/b59ac464-6dc0-4b75-bb86-bd63696738cb

Joy UI is broken too.

cc @mj12albert as owning the select component: https://www.notion.so/mui-org/Components-Inputs-ecd48c9afe354bda8ecda3e96abc8c3c

### Your environment 🌎

@mui/base v5.0.0-beta.8

### LINKED ISSUE #54: [RFC][Select] Rendering the selected value in SSR & during hydration
### What's the problem? 🤔

Raised in https://github.com/mui/base-ui/issues/37, to refine the `renderValue` API to support rendering `Select`'s selected value in SSR and during hydration

### What are the requirements? ❓

- I would expect to be able to render the value to look exactly like a (custom) option
- Avoid breaking changes required of Material UI v6

### 1. Provide an `options` prop  

`useSelect` already accepts an optional [`options` param](https://mui.com/base-ui/react-select/hooks-api/#prop-options), though it will ignore JSX children

The `Select` component does not pass (or even accept) `options` to the underlying `useSelect`.

Though it may be asking too much from the user, it could be optional for those that need it.

Related - possibly related, raised in this (old) [issue](https://github.com/mui/material-ui/issues/29497#issuecomment-960659540), why options aren't provided by `renderValue`:
```
const options = [ ... ];

return (
  <Select
    renderValue={value => {
      const item = options.find(option => option.value === value ); 
      return item.label
    }}
  />
)
```

### 2. An `Autocomplete`-like API

Suggested in https://github.com/mui/base-ui/issues/37

Autocomplete has [`getOptionLabel`](https://mui.com/material-ui/api/autocomplete/#Autocomplete-prop-getOptionLabel) for the simple case of rendering a string (usually when the `value` and `option` are the same type), and [`renderOption`](https://mui.com/material-ui/api/autocomplete/#Autocomplete-prop-renderOption) that is more like a render prop.

Applying this pattern to Base's Select could look like:

- Keep the `renderValue: (selectedValue) => ReactNode` for the "simple" case, maybe rename it to be the equivalent of `getOptionLabel` (e.g. `getValueLabel`? `getValueDisplay`?)
- Have a "proper" render prop for the value that provides additional arguments, e.g. `ownerState`

This may allow more flexibility, but it is quite different from Material UI's current API

### Proposed solution 🟢

I think Base UI's Select's current `renderValue` is already quite sufficient, it has parity with Material UI, and the layout shift [issue](https://github.com/mui/material-ui/pull/38796) was fixed

Having two props for rendering the value like Autocomplete doesn't seem worth it for the additional mental overhead of a new prop, and it would deviate more from the current Select APIs

Maybe it would be enough if we pass `ownerState` to `renderValue` as a 2nd argument to provide more customization flexibility. At the risk of bloating this too much, we could even additionally accept `options` and pass that into `ownerState` as well

### Resources and benchmarks 🔗

- https://react-spectrum.adobe.com/react-aria/Select.html#dynamic-collections
-

### LINKED ISSUE #56: [Select] Highlight doesn't highlight properly if an Option has the value null
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/keen-david-z2r399?file=/src/Demo.tsx

The reproduction is taken from the [docs](https://mui.com/base-ui/react-select/).

Steps:

1. Open the first select
2. Press down-arrow key multiple times
3. Press up-arrow key multiple times

### Current behavior 😯

Pressing the down-arrow key doesn't highlight anything but pressing the up-arrow key highlights normally excluding the null value. For the second select, pressing the down-arrow key only highlights the first option and the up-key can only highlight the bottom two options. 

### Expected behavior 🤔

Pressing either direction key should skip null value Options and highlight the first possible non-null value

### Context 🔦

Found while testing

### Your environment 🌎

<details>
This was done using Firefox Browser. For environment see linked codesandbox.io
</details>

### LINKED ISSUE #64: [Select] Mouse pointer doesn't steal focus on hover
Mousing over an Option should steal focus. Currently, mousing over Options doesn’t move focus to that Option.

https://github.com/mui/material-ui/assets/4696105/a650edd9-8c1e-4fbf-a760-701c11bccd36

Compare it to the Menu which highlights items on hover (merged to master but not released yet in Base UI as of Jan 30):

https://github.com/mui/material-ui/assets/4696105/9392bb0b-73a3-4a57-b71a-45df2238f900

The implementation should be similar to the changes in Menu done in mui/material-ui#40755

**Search keywords**:

### LINKED ISSUE #65: [Select] Typeahead doesn't work on a closed Select
When a Select is closed but focused, pressing a character key should open it and move focus to the first option matching the pressed key. Currently, pressing character keys on a closed Select has no effect.

**Search keywords**:

### LINKED ISSUE #66: [Select] Support opening the Select and selecting an option with one click
Similarly to the native macOS menus, we could support executing opening the Select and selecting actions with only one click. This requires the Select to open on pointerdown and options to be selected on pointerup.
This way, users will be able to press the mouse button on the Select, move to an option while still holding the button, and finally release the button over the option to select it.

**Search keywords**:

### LINKED ISSUE #82: [Select] The macOSVoiceOver doesn't read current value correctly on Safari
### Steps to reproduce

https://mui.com/base-ui/react-select/

Steps:
1. On MacOS run VoiceOver.
2. Open https://mui.com/base-ui/react-select/ in Safari.
3. Tab to the demo control in the Introduction section.

### Current behavior

When VoiceOver reads the Select control (without it being opened), it announces its value with the last character missing and with a comma added to the beginning. For example for the demo on the MUI site, it announces the three values like so:

- Documentation:   ", Documentatio"
- Components:   ", Component" 
- Features:   ", Feature"

VO screenshot

We have used it in an implementation (unfortunately I can't provide access) and it is sometimes misses out the last two characters and sometimes adds "misspelt" before the value.

This only happens in Safari, not when using Chrome.

### Expected behavior

VoiceOver should announce the value as it is displayed.

### Context

_No response_

### Your environment

MacOS 14.1.1 Sonoma
Safari 17.1

Excuse my ignorance but I don't know how to run `npx @mui/envinfo`. Where should I do this?

**Search keywords**: Select VoiceOver

### PR DESCRIPTION
**Pull request by atomiks**
Preview: https://deploy-preview-541--base-ui.netlify.app/components/react-select/

- Closes https://github.com/mui/base-ui/issues/547
- Closes https://github.com/mui/base-ui/issues/476
- Closes https://github.com/mui/base-ui/issues/327
- Closes https://github.com/mui/base-ui/issues/328
- Closes https://github.com/mui/base-ui/issues/217
- Closes https://github.com/mui/base-ui/issues/8
- Closes https://github.com/mui/base-ui/issues/82
- Closes https://github.com/mui/base-ui/issues/66
- Closes https://github.com/mui/base-ui/issues/65
- Closes https://github.com/mui/base-ui/issues/64
- Closes https://github.com/mui/base-ui/issues/56
- Closes https://github.com/mui/base-ui/issues/54 (solved via `Select.Value` `placeholder` prop)
- Closes https://github.com/mui/base-ui/issues/7 (TODO: provide a warning if `defaultValue` / `value` don't match any of the options)
- Closes https://github.com/mui/base-ui/issues/37 (seem the same as #54)
- Closes https://github.com/mui/base-ui/issues/14 (now invalid)

TODO:

- [x] Integrate with `useField`
- [x] Renamed `alignMethod` prop to `alignOptionToTrigger`

Olivier's edit: the v2 of https://github.com/mui/material-ui/pull/8023 😄

### CODE REVIEW

File: packages/mui-base/src/Select/Trigger/SelectTrigger.tsx [hunk 1]
```diff
@@ -0,0 +1,129 @@
...
+    [fieldOwnerState, open],
+  );
+
+  const { renderElement } = useComponentRenderer({
+    render: render ?? 'div',
+    className,
+    ownerState,
+    propGetter: (externalProps) => getTriggerProps(getRootTriggerProps(externalProps)),
+    customStyleHookMapping: commonStyleHooks,
+    extraProps: otherProps,
```
Comment (michaldudak) [inline packages/mui-base/src/Select/Trigger/SelectTrigger.tsx:62]: It would be great if the Trigger had a CSS variable with the width of the popup, so it can match it (as in native OS controls)

File: packages/mui-base/src/Select/Root/SelectRoot.tsx [hunk 2]
```diff
@@ -0,0 +1,200 @@
...
+    /**
+     * If `true`, the Select is disabled.
+     *
+     * @default false
+     */
+    disabled?: boolean;
+    /**
+     * The value of the select.
+     */
+    value?: string;
```
Comment (michaldudak) [inline packages/mui-base/src/Select/Root/SelectRoot.tsx:90]: Similarly to RadioGroup (and the previous implementation of the Select), we should accept any value, not just a string.
We can then treat `value: null` as no selected option

File: packages/mui-base/src/Select/Trigger/SelectTrigger.tsx (hunk 1 above)
Comment (atomiks) [reply packages/mui-base/src/Select/Trigger/SelectTrigger.tsx:62]: Do you mean the inverse? `--anchor-width` for popup is available. The trigger can't know the width of the popup when it's not mounted

Comment (michaldudak) [reply packages/mui-base/src/Select/Trigger/SelectTrigger.tsx:62]: No, I didn't mean the inverse. Native OS selects adapt their width to the longest option. Perhaps this could be an option when keepMounted=true.

Comment (atomiks) [reply packages/mui-base/src/Select/Trigger/SelectTrigger.tsx:71]: That's true, but I'm hesitant to add something that doesn't work by default. Furthermore,  it's likely very performance intensive with longer lists to calculate as you'll need to measure every option with `getBoundingClientRect` to calculate the largest one. It also doesn't work during SSR, so will cause layout shift. It's likely something that should be hardcoded by the user if necessary.

**Comment by michaldudak** [comment]
Could you please review [the list of reported Select bugs](https://github.com/mui/base-ui/issues?q=is%3Aissue+is%3Aopen+label%3A%22component%3A+select%22) and set this PR to close the ones that will be fixed by it?

**Comment by flaviendelangle** [comment]
When you open the select, the page scrollbar disappears causing a layout shift on the right navbar in the doc (https://deploy-preview-541--base-ui.netlify.app/components/react-select/)

The `@mui/material` select also removes the scrollbar but there is no layout shift (https://mui.com/material-ui/react-select/)

**Comment by atomiks** [comment]
@flaviendelangle interesting. The `padding-right: 15px` for the scrollbar width offset once it disappears prevents the main content from shifting but not the right navbar content (and end of the top navbar)

**Comment by michaldudak** [comment]
I'm wondering if we should prevent scrolling by default at all. I find it annoying when I open a select and something else changes appearance (=the scrollbar disappears). Native implementations differ in this matter - iOS prevents scrolling but doesn't hide the scrollbar, while Windows closes the popup when the page scrolls.
IMO locking the scroll is more important in modal windows.

I found an issue that's likely related to scroll locking: https://codesandbox.io/p/sandbox/q7qfjg - when you open the select, there's a small layout shift and you're able to scroll the page horizontally until the whole trigger disappears.

File: docs/data/components/select/select.mdx [hunk 3]
```diff
@@ -0,0 +1,349 @@
...
+Two different methods to align the popup are available:
+
+- `alignMethod="item"` (default)
+- `alignMethod="trigger"`
+
+```jsx
+<Select.Root alignMethod="trigger">
+```
+
+- **`item`**: aligns the popup such that the selected option inside of it appears centered over the trigger. If there's not enough space, it falls back to `trigger` anchoring. This method is useful as it allows the user to select the an option in a single click or "pointer cycle" (pointer down, pointer move, pointer up). This is the native behavior on macOS. The scroll arrow components must be used to ensure this is the case.
```
Comment (michaldudak) [inline docs/data/components/select/select.mdx:150]: Doesn't the "trigger" option allow selecting with a single click?

Comment (atomiks) [reply docs/data/components/select/select.mdx:150]: Yes but only if there's no scrollable content

**Comment by atomiks** [comment]
> I'm wondering if we should prevent scrolling by default at all. I find it annoying when I open a select and something else changes appearance (=the scrollbar disappears).

The scroll locking changes we made in #604 prevents layout shift issues from disappearing scrollbars. The scroll lock is necessary with the item align anchoring because you can `wheel` the popup to reveal more items, but this can cause the page to scroll. It's not locked for the `trigger` align method.

> I found an issue that's likely related to scroll locking: https://codesandbox.io/p/sandbox/q7qfjg - when you open the select, there's a small layout shift and you're able to scroll the page horizontally until the whole trigger disappears.

This looks like a bug with the .SelectPopup `min-width` style that doesn't limit itself by the `--available-width`.

This solves it:
```css
  min-width: min(var(--available-width), calc(var(--anchor-width) + 20px));
```

There's a thread discussing default "functional styles" to apply to these elements and an API to override them in a thread in the base-ui channel. This could help prevent certain issues like this, including:

- Making the popup scrollable by default
- Limiting the popup's size to the available space (but the above calculation requires the user to use their own custom padding value)

**Comment by michaldudak** [comment]
> This looks like a bug with the .SelectPopup min-width style that doesn't limit itself by the --available-width.
>
> This solves it:

The repro was taken directly from the demos, so they'll need to have the styles updated.

File: packages/mui-base/src/Select/OptionText/SelectOptionText.tsx [hunk 4]
```diff
@@ -0,0 +1,108 @@
+import * as React from 'react';
```
Comment (michaldudak) [inline packages/mui-base/src/Select/OptionText/SelectOptionText.tsx:1]:
```suggestion
'use client';
import * as React from 'react';
```

File: packages/mui-base/src/Select/Popup/SelectPopup.tsx [hunk 5]
```diff
@@ -0,0 +1,111 @@
...
+import { commonStyleHooks } from '../utils/commonStyleHooks';
+import { useComponentRenderer } from '../../utils/useComponentRenderer';
+import { useForkRef } from '../../utils/useForkRef';
+import type { CustomStyleHookMapping } from '../../utils/getStyleHookProps';
+import { useSelectPopup } from './useSelectPopup';
+
+const customStyleHookMapping: CustomStyleHookMapping<SelectPopup.OwnerState> = {
+  ...commonStyleHooks,
+  entering(value) {
+    return value ? { 'data-select-entering': '' } : null;
```
Comment (michaldudak) [inline packages/mui-base/src/Select/Popup/SelectPopup.tsx:17]: I saw you renamed it in the Menu to 'data-entering' and 'data-exiting' (https://github.com/mui/base-ui/pull/638/files#diff-e31760a8ce5d872099c8c8aa212adac7e10ad678504402a0b963903373cbda26). Let's make it consistent, then.

File: packages/mui-base/src/Select/Positioner/useSelectPositioner.tsx [hunk 6]
```diff
@@ -0,0 +1,254 @@
...
+          hiddenStyles.pointerEvents = 'none';
+        }
+
+        return mergeReactProps(externalProps, {
+          tabIndex: -1,
+          inert: open ? undefined : 'true',
+          style: {
+            ...positionerStyles,
+            ...hiddenStyles,
+            zIndex: 2147483647, // max z-index
```
Comment (michaldudak) [inline packages/mui-base/src/Select/Positioner/useSelectPositioner.tsx:71]: This value is used several times across the codebase. Should be extracted to a const.

File: packages/mui-base/src/Select/Positioner/SelectPositionerContext.ts [hunk 7]
```diff
@@ -0,0 +1,36 @@
...
+
+if (process.env.NODE_ENV !== 'production') {
+  SelectPositionerContext.displayName = 'SelectPositionerContext';
+}
+
+export function useSelectPositionerContext() {
+  const context = React.useContext(SelectPositionerContext);
+  if (context === null) {
+    throw new Error(
+      'Base UI: <Select.Popup> must be used within the <Select.Positioner> component',
```
Comment (michaldudak) [inline packages/mui-base/src/Select/Positioner/SelectPositionerContext.ts:32]: This assumes `SelectPositionerContext` is only used in Select.Popup

File: packages/mui-base/src/Select/Positioner/SelectPositionerContext.ts [hunk 8]
```diff
@@ -0,0 +1,36 @@
+'use client';
+import * as React from 'react';
+import type { Side } from '@floating-ui/react';
+
+export interface SelectPositionerContext {
```
Comment (michaldudak) [inline packages/mui-base/src/Select/Positioner/SelectPositionerContext.ts:5]: The last 3 fields could benefit from a brief JSDoc description

File: packages/mui-base/src/Select/Root/useSelectRoot.tsx
Comment (michaldudak) [inline packages/mui-base/src/Select/Root/useSelectRoot.tsx:1]: The previous implementation supported multiple selection. Do you plan to add it here as well or in a separate component?

File: packages/mui-base/src/Select/Root/useSelectRoot.tsx [hunk 9]
```diff
@@ -0,0 +1,365 @@
...
+    activeIndex,
+    selectedIndex,
+    loop,
+    onNavigate: setActiveIndex,
+  });
+
+  const typeahead = useTypeahead(floatingRootContext, {
+    listRef: labelsRef,
+    activeIndex,
+    resetMs: 500,
```
Comment (michaldudak) [inline packages/mui-base/src/Select/Root/useSelectRoot.tsx:176]: The default should be consistent with Menu's typeahead. A shared value referenced from both components will ensure they don't drift apart.

File: packages/mui-base/src/Select/Separator/SelectSeparator.tsx
Comment (michaldudak) [inline packages/mui-base/src/Select/Separator/SelectSeparator.tsx:1]: Once https://github.com/mui/base-ui/pull/535 is merged, Select can use it directly.

File: packages/mui-base/src/Select/Value/SelectValue.tsx [hunk 10]
```diff
@@ -0,0 +1,85 @@
+import * as React from 'react';
```
Comment (michaldudak) [inline packages/mui-base/src/Select/Value/SelectValue.tsx:1]:
```suggestion
'use client';
import * as React from 'react';
```

File: packages/mui-base/src/Select/Separator/SelectSeparator.tsx [hunk 11]
```diff
@@ -0,0 +1,69 @@
+import * as React from 'react';
```
Comment (michaldudak) [inline packages/mui-base/src/Select/Separator/SelectSeparator.tsx:1]:
```suggestion
'use client';
import * as React from 'react';
```

File: packages/mui-base/src/Select/Root/useSelectRoot.tsx
Comment (atomiks) [reply packages/mui-base/src/Select/Root/useSelectRoot.tsx:1]: Given the potential complexity, a separate component + we'd need to discuss such an API first

**Comment by michaldudak** [comment]
The Select.Root should be generic over its value (as in the previous implementation), so that `value`, `defaultValue`, and `onValueChange` parameter types are the same.

**Comment by oliviertassinari** [comment]
I imagine we won't support https://github.com/mui/material-ui/issues/20402#issuecomment-619275339 just yet:

https://github.com/user-attachments/assets/95dc7af4-6413-4053-8ddf-21ecd022968c

https://codesandbox.io/p/sandbox/magical-sara-zqhf6x. I think we should open a new issue for it, e.g. https://x.com/devongovett/status/1248306411508916224. One mistake I did there back in the days is I think to not compare values with autocompelte on toLowerCase() mode, like Chrome native select seems to do.

File: packages/mui-base/src/Select/Root/SelectRoot.test.tsx [hunk 12]
```diff
@@ -0,0 +1,242 @@
...
+      fireEvent.click(trigger);
+
+      await flushMicrotasks();
+
+      expect(screen.getByRole('option', { name: 'a', hidden: false })).to.have.attribute(
+        'data-selected',
+        'true',
+      );
+
+      rerender(
```
Comment (oliviertassinari) [inline packages/mui-base/src/Select/Root/SelectRoot.test.tsx:97]: Why not call `setProps()` so we don't have to duplicate the rest of the component code?

**Comment by atomiks** [comment]
@oliviertassinari actually I did try to add support for it but I couldn't seem to get even the native select to autofill in my browser. I'll try to work off this demo instead.

**Review by michaldudak — COMMENTED** [review]
There's an issue when using objects as options - the component complains the selected option is not present among the available options: https://codesandbox.io/p/sandbox/upbeat-sun-v7yx2k (this fails in both controlled and uncontrolled mode).

Additionally, FYI, we briefly discussed rendering a native select on mobile devices by default. This could be done in a separate PR once we flesh out the details, but it's good to keep it in mind.

File: docs/data/components/select/SelectIntroduction/system/index.tsx [hunk 13]
```diff
@@ -0,0 +1,194 @@
...
+export default function SelectIntroduction() {
+  return (
+    <Select.Root defaultValue="system" onValueChange={(v) => console.log(v)}>
+      <SelectTrigger aria-label="Select font">
+        <Select.Value placeholder="System font" />
+        <SelectDropdownArrow />
+      </SelectTrigger>
+      <Select.Positioner sideOffset={5}>
+        <SelectScrollUpArrow
+          render={(props) => (
```
[the remark this answers is not in the document]
Comment (atomiks) [reply docs/data/components/select/SelectIntroduction/system/index.tsx:16]: I'm not seeing this type error locally. Possibly need to restart your TS server

**Comment by mnajdova** [comment]
> By default, the selected option inside the popup is aligned to the trigger element. This can be disabled with the alignOptionToTrigger prop

Maybe it's because I am coming from Mateiral UI, but I would prefer aligning the popup to the trigger to be default behavior.

File: packages/mui-base/src/utils/useAnchorPositioning.ts [hunk 14]
```diff
@@ -86,9 +95,14 @@ export function useAnchorPositioning(
...
     mounted = true,
     trackAnchor = true,
+    allowAxisFlip = true,
+    open,
     nodeId,
+    inner: innerMiddleware,
+    innerOptions = {},
   } = params;
 
+  const standardMode = innerOptions.touchModality || !(!innerOptions.fallback && innerMiddleware);
```
Comment (michaldudak) [inline packages/mui-base/src/utils/useAnchorPositioning.ts:105]: IMO this deserves a comment explaining what it is and what's the other mode.

File: packages/mui-base/src/utils/floating.ts
Comment (michaldudak) [inline packages/mui-base/src/utils/floating.ts:1]: Why is this file called floating.ts? "constants" would make more sense.

File: packages/mui-base/src/index.ts [hunk 15]
```diff
@@ -7,12 +7,13 @@ export * from './Field';
 export * from './Fieldset';
 export * from './Form';
 export * from './Menu';
-export * from './NumberField';
+export * from './Select';
```
Comment (michaldudak) [inline packages/mui-base/src/index.ts:10]: Something wrong happened here

```suggestion
export * from './NumberField';
```

File: packages/mui-base/src/Tooltip/Positioner/useTooltipPositioner.ts [hunk 16]
```diff
@@ -39,7 +40,7 @@ export function useTooltipPositioner(
             ...hiddenStyles,
             maxWidth: 'var(--available-width)',
             maxHeight: 'var(--available-height)',
-            zIndex: 2147483647, // max z-index
+            zIndex: MAX_Z_INDEX, // max z-index
```
Comment (michaldudak) [inline packages/mui-base/src/Tooltip/Positioner/useTooltipPositioner.ts:43]: This comment isn't necessary anymore

File: packages/mui-base/src/utils/useAnchorPositioning.ts (hunk 14 above)
Comment (atomiks) [reply packages/mui-base/src/utils/useAnchorPositioning.ts]: `alignPopupToTrigger` (the inverse of `alignOptionToTrigger`) should now be the name of this

**Comment by atomiks** [comment]
> Maybe it's because I am coming from Mateiral UI, but I would prefer aligning the popup to the trigger to be default behavior.

This is the most common default, though Radix uses the `alignOptionToTrigger` default, as does macOS. Figma also uses this for their selects, so it does exist on the web outside Radix. With scrollable content (large select option lists), it results in the best UX since selection can be done in one single pointer cycle. The docs will list reasoning for certain choices. This will be explained in a documentation template doc on Notion.

**Review by michaldudak — APPROVED** [review]
Looks good (assuming the tests are fixed)!

**Review by colmtuite — APPROVED** [review]

**Comment by mnajdova** [comment]
1. What's the heuristic about giving up on the align option to trigger when close to the edge? I am asking because we have kind of a different behavior based on the options, e.g.

Screenshot 2024-11-12 at 10 31 32
Screenshot 2024-11-12 at 10 31 42

I would assume these two to behave the same way (we have space for the scrolling arrow in both scenarios).

2. Can we explain in [this](https://deploy-preview-541--base-ui.netlify.app/components/react-select#align-method) section why the change of the aligning affects whether the scroll is blocked or not. It could be surprising that just because you want things to be aligned differently it affects whether the scroll on the page is available or not.

3. Based on https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-select-only/, we shouldn't support circular navigation when using Up/Down Arrow => we should set `loop: false` in the `useListNavigation`.

Screenshot 2024-11-12 at 10 35 25

4. Based on https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-select-only/ we should open the listbox when user types printable characters with setting active descendant on the right item:

> If the combobox is collapsed and the user types printable characters, the listbox is displayed and receives accessibility focus via aria-activedescendant. This enables users to perceive the presence of the options, and enables assistive technology users to comprehend the size of the list of options.

5. Are we handling Home and End keys?

**Comment by atomiks** [comment]
> 1. What's the heuristic about giving up on the align option to trigger when close to the edge? I am asking because we have kind of a different behavior based on the options, e.g.

If the `min-height` is 100px or less (can be configured in their CSS), or if the reference is within 20px of the viewport edge, it falls back to standard anchoring. I felt the UX was much better in this case, matching macOS' fallback behavior.

> 2. 

Fair point!

> 3.

Can change this, not sure if we should provide an option if so.

> 4. 

This seems to be a new pattern or suggestion that I haven't seen before, and the native select doesn't appear to do this. It doesn't seem critical to implement for now.

> 5.

Yes, Home/End are handled

File: packages/mui-base/src/Select/Option/SelectOption.tsx [hunk 17]
```diff
@@ -0,0 +1,334 @@
...
+ */
+const SelectOption = React.forwardRef(function SelectOption(
+  props: SelectOption.Props,
+  forwardedRef: React.ForwardedRef<HTMLDivElement>,
+) {
+  const { value: valueProp = null, label, ...otherProps } = props;
+
+  const listItem = useCompositeListItem({ label });
+  const { activeIndex, selectedIndex, setActiveIndex } = useSelectIndexContext();
+  const { getItemProps, setOpen, setValue, open, selectionRef, typingRef, valuesRef, popupRef } =
```
Comment (michaldudak) [inline packages/mui-base/src/Select/Option/SelectOption.tsx:225]: Can this be moved to InnerSelectOption? It seems that these values don't change on each option highlight (except maybe `getItemProps`?)

File: packages/mui-base/src/Select/Option/SelectOption.tsx [hunk 18]
```diff
@@ -0,0 +1,334 @@
...
+  const contextValue = React.useMemo(
+    () => ({
+      selected: isSelected,
+      indexRef,
+    }),
+    [isSelected, indexRef],
+  );
+
+  return (
+    <SelectOptionContext.Provider value={contextValue}>
```
Comment (michaldudak) [inline packages/mui-base/src/Select/Option/SelectOption.tsx:258]: It seems that this provider can be rendered by InnerSelectOption

File: packages/mui-base/src/Select/Option/SelectOption.tsx (hunk 17 above)
Comment (atomiks) [reply packages/mui-base/src/Select/Option/SelectOption.tsx:225]: Looks like you may be right (`getItemProps` also changes infrequently). I'll try to refactor this.

Comment (atomiks) [reply packages/mui-base/src/Select/Option/SelectOption.tsx:225]: Consuming the root context inside the memoized component is risky as any time the root context changes it will cause every option to re-render. Even if they don't change on each option highlight, they can change on other unrelated state changes. Minor refactorings could introduce issues unknowingly as well.

**Review by michaldudak — COMMENTED** [review]
The performance of large lists is still not quite good. I  played a bit with the profiler and identified that quite a lot of time is spent in FloatingFocusManager's handleMutation (https://github.com/floating-ui/floating-ui/blob/master/packages/react/src/components/FloatingFocusManager.tsx#L651). I initially thought that the slowdown may be caused by focusing each item on hover, but Radix does is as well and yet their Select feels snappier. IMO we can merge this PR so that this branch doesn't live for too long, but we should then investigate what can be done to make it even faster.
