### PR TITLE
[NumberField] Component and Hook

### LINKED ISSUE #185: [number field] Implement NumberField with new API
### Summary

Replaces the `NumberInput` component.

This is the place to gather ideas, measure interest and discuss the API and implementation details of the `NumberField` component and hook.

## Anatomy

```js
<NumberField>
  <NumberField.Group>
    <NumberField.Input />
    <NumberField.Decrement />
    <NumberField.Increment />
    <NumberField.Scrubber />
  </NumberField.Group>
</NumberField>
```

### **Root**

Rendered element: `div`

<table> <thead> <tr> <th>prop</th> <th>type</th> <th>default</th> <th>description</th> </tr> </thead> <tbody> <tr> <td>defaultValue</td> <td>number</td> <td></td> <td></td> </tr> <tr> <td>id</td> <td></td> <td></td> <td></td> </tr> <tr> <td>min</td> <td>number</td> <td></td> <td></td> </tr> <tr> <td>max</td> <td>number</td> <td></td> <td></td> </tr> <tr> <td>step</td> <td>number</td> <td>1</td> <td></td> </tr> <tr> <td>largeStep</td> <td>number</td> <td>10</td> <td></td> </tr> <tr> <td>required</td> <td>boolean</td> <td></td> <td></td> </tr> <tr> <td>disabled</td> <td>boolean</td> <td></td> <td></td> </tr> <tr> <td>invalid</td> <td>boolean</td> <td></td> <td></td> </tr> <tr> <td>autoFocus</td> <td>boolean</td> <td></td> <td></td> </tr> <tr> <td>children</td> <td></td> <td></td> <td></td> </tr> <tr> <td>readOnly</td> <td>boolean</td> <td></td> <td></td> </tr> <tr> <td>name</td> <td>string</td> <td></td> <td></td> </tr> <tr> <td>value</td> <td>number</td> <td></td> <td></td> </tr> <tr> <td>onChange</td> <td>function</td> <td></td> <td></td> </tr> <tr> <td>format</td> <td>Intl.NumberFormatOptions</td> <td></td> <td></td> </tr> </tbody> </table>

Other props (unnamed):

- Ability to scrub the input with the `wheel`
- Locale for `format`

### **Group**

Rendered element: `div`

All `div` attrs.

### **Input**

Rendered element: `<input type="text" />`

All `input` attrs.

### **Decrement**

Rendered element: `button` 

All `button` attrs.

### **Increment**

Rendered element: `button` 

All `button` attrs.

### **Scrubber**

Rendered element: `span` 

All `span` attrs.

## Benchmarks

- https://react-spectrum.adobe.com/react-aria/NumberField.html
- https://chakra-ui.com/docs/components/number-input

### Examples

_No response_

### Motivation

_No response_

**Search keywords**: number field, number input

### LINKED ISSUE #224: [number field] Disable focus on mobile
### Steps to reproduce

https://mui.com/base-ui/react-number-input/#customization

https://github.com/mui/base-ui/assets/3165635/ee32167a-b35c-4278-8b07-631a5edadff3

### Current behavior

The input is focused on mobile, so the virtual keyboard triggers

### Expected behavior

No input focus on mobile when using the control. 

### Context

See https://www.notion.so/mui-org/core-Input-Number-component-364825a7bec94381809ac11ff05b4cc0. For eample https://react-spectrum.adobe.com/blog/how-we-internationalized-our-numberfield.html looks correct to me. Focus on desktop, no focus on mobile.

### Your environment

@mui/base@5.0.0-beta.36

**Search keywords**: focus

### PR DESCRIPTION
**Pull request by atomiks**
- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/base-ui/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).

Closes #185
Closes #224 

Preview: https://deploy-preview-186--base-ui.netlify.app/base-ui/react-number-field/

**TODO:**

- [x] Complete tests
- [x] Documentation

---

- [x] When merged, use the mergeEventHandlers / mergeProps function written by Michal to significantly simplify the event handler definitions.
- [x] Remove the “scrub past“ distance when a max/min is specified, so it doesn't take too long to "get back".
- [x] Fix the “magnifier” appearing on iOS when press-holding the stepper buttons.
- [x] Add `teleportDistance` (or other name) prop to loop closer to the input compared to the viewport.
- [x] Fix bug when there’s a “-“ and you can’t type “-“ again when all content has been selected to be overwritten (e.g. paste).
- [x] Fix virtual cursor being too big when zooming (cmd+ or pinch-zoom). It should invert the scale to match the OS size. *[Update: was unable to figure out how to reliably detect native browser zoom. Only pinch zoom is handled.]*
- [x] Fix 1px sensitivity to 2px for scrub area, and add sensitivity prop.
- [x] Add Home and End key support if min/max are specified.
- [x] Add `displayName` to Contexts.
- [x] Ensure all imports use the path rather than the top-level barrel.
- [x] Cache `Intl.NumberFormat` usage.
- [x] Match various nits/conventions pointed out by Olivier.
- [x] Dynamically change the `inputMode="numeric"` prop for iOS when appropriate, which doesn't show a negative sign in the software keyboard, it must be "text".
- [x] Research if spinbutton ARIA props become necessary for iOS when `inputMode` is "text".
- [x] The virtual cursor should be automatically portalled to the body.
- [x] Move `ScrubArea` logic into the `useNumberField` hook, or possibly a separate hook. Depends how granular the tree-shaking could possibly be for this functionality.
- [x] Automatically remove floating point errors

### CODE REVIEW

File: packages/mui-base/src/utils/useControlled.ts [hunk 1]
```diff
@@ -0,0 +1,4 @@
+/**
+ * @ignore - internal hook.
+ */
+export { unstable_useControlled as useControlled } from '@mui/utils';
```
Comment (flaviendelangle) [inline packages/mui-base/src/utils/useControlled.ts:4]: Should it be imported from `@mui/utils/useControlled` to allow for tree shaking in dev mode? 
@mnajdova I would love for us to settle on a clear guideline of which packages should be tree-shakable in dev (and always have lint rules to forbid root imports), and clearly state that for the others we don't care.
Because right now we tend to try to have nested imports, but not always, which totally defeats the purpose.

File: packages/mui-base/src/utils/getElementDocument.ts [hunk 2]
```diff
@@ -0,0 +1,8 @@
+/**
+ * Get the document associated with an element.
+ * @param element
+ * @returns `Document` associated with the element
+ */
+export function getElementDocument(element: Element | null) {
+  return element?.ownerDocument || document;
```
Comment (flaviendelangle) [inline packages/mui-base/src/utils/getElementDocument.ts:7]: We have an `ownerDocument` on `@mui/utils` which does exactly this

File: packages/mui-base/src/utils/useControlled.ts (hunk 1 above)
Comment (mnajdova) [reply packages/mui-base/src/utils/useControlled.ts:4]: Thanks for nudging me. Is there a concern with always using nested imports? Agree, a lint rule could help, we likely have one if I am not mistaken. Even if it is not for tree shaking, we've seen this as an optimization for Pigment CSS too, as it needs to go through fewer files when the imports are nested.

Comment (flaviendelangle) [reply packages/mui-base/src/utils/useControlled.ts:4]: >  Is there a concern with always using nested imports?

For me the only problem is that if 19 persons always use nested imports for the 20th decide that it's not worth the effort and uses one root import, it can destroy the whole optilmization.
So I think having an explicit decision can help us enforce the rule.

But my personal opinion, I think having nested imports as a general rule for our codebase would be nice.

File: packages/mui-base/src/utils/getElementDocument.ts (hunk 2 above)
Comment (atomiks) [reply packages/mui-base/src/utils/getElementDocument.ts:7]: Thank you. Fixed!

File: packages/mui-base/src/utils/useControlled.ts (hunk 1 above)
Comment (atomiks) [reply packages/mui-base/src/utils/useControlled.ts]: Updated

**Comment by oliviertassinari** [comment]
Rebased on HEAD. It seems to fix Circle CI, I don't know why.

**Comment by michaldudak** [comment]
It might be subjective, but the scrubber feels too sensitive. Changing value on every pixel of pointer movement may be too fast. Figma seems to update the value every two pixels (or perhaps they take pixel density into consideration?). We could make this configurable by adding the `sensitivity` prop to the ScrubArea (being the number of pixels the pointer should move before the value is updated)

**Comment by atomiks** [comment]
@michaldudak yeah you're right, previously it was 2px but I must have changed something that reverted it back to 1px. Will fix.

**Review by colmtuite — CHANGES_REQUESTED** [review]
Tested on Chrome, Safari, Safari iOS, and Chrome iOS. Feedback/thoughts so far:

- `ScrubAreaCursor` is missing from the docs anatomy section.
- Seems like we don't have the teleport threshold thingy prop on `ScrubAreaCursor` yet? Are you planning to add that?
- Should scrubbing start from where the pointer was when scrubbing began, or when the pointer direction changes during scrubbing? Idk how to explain wtf I'm on about here 🤣  It's noticeable when `min` and `max` are set. If you set `max`, then scrub way beyond the `max` value, you need to scrub all the way back down before the value decrements. Perhaps it could begin decrementing immediately when the pointer direction changes?
- The `largeStep` logic seems odd to me. I expected it to just increment/decrement the value by whatever the `largeStep` value is?
- `smallStep` doesn't seem to be working for me. Nothing happens when I hold `cmd` and then increment/decrement.

Still to test: formatting options.

**Comment by atomiks** [comment]
Thank you @colmtuite! 

> Seems like we don't have the teleport threshold thingy prop on ScrubAreaCursor yet? Are you planning to add that?

Yes, will add.

> Should scrubbing start from where the pointer was when scrubbing began, or when the pointer direction changes during scrubbing? Idk how to explain wtf I'm on about here 🤣 It's noticeable when min and max are set. If you set max, then scrub way beyond the max value, you need to scrub all the way back down before the value decrements. Perhaps it could begin decrementing immediately when the pointer direction changes?

No I know exactly what you're talking about because I intentionally made it work the way it currently does 😆 . I don't know if it's correct but it felt more right to me — but if you scrub _too_ far it takes too long to "get back" indeed.

https://github.com/mui/base-ui/pull/186/files#diff-baaa930fa9d9c0612e404a05ea9e8e510a5f4122cd1348a24f94eecdce5cd1c4R118-R122

```js
  // When scrubbing gets clamped, we want to keep the raw value to be able to ensure changing scrub
  // direction only changes the value once the pointer moves past the point at which the value
  // started being clamped.
  const latestValueRef = useLatestRef(value);
  const rawValueRef = React.useRef(value);
```

> The largeStep logic seems odd to me. I expected it to just increment/decrement the value by whatever the largeStep value is?

The `step` logic in `react-aria` and the current Base UI `NumberInput` not only increments but also snaps, at least for `integer` values (the default). So `largeStep` also snaps, but I'm not sure if that's right?

> `smallStep` doesn't seem to be working for me. Nothing happens when I hold cmd and then increment/decrement.

Yeah, I made it `1` by default, so it doesn't do anything. It doesn't work with the default `integer` formatting. It's useful for currencies, percentages, etc.

File: packages/mui-base/src/NumberField/utils/parse.ts [hunk 3]
```diff
@@ -0,0 +1,39 @@
+export const HAN_NUMERALS = ['零', '一', '二', '三', '四', '五', '六', '七', '八', '九'];
+export const ARABIC_NUMERALS = ['٠', '١', '٢', '٣', '٤', '٥', '٦', '٧', '٨', '٩'];
+
+export function getNumberLocaleDetails(options?: Intl.NumberFormatOptions) {
+  const parts = new Intl.NumberFormat(undefined, options).formatToParts(1111.1);
```
Comment (oliviertassinari) [inline packages/mui-base/src/NumberField/utils/parse.ts:5]: I don't see this working at scale, the locale is set to `undefined`, so per https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat#locales, it uses the "default locale". So

- Developers can't force a locale, e.g. fr-FR
- During SSR hydration, there could be a mismatch, either because the server doesn't have the same CLDR data as the browser or because the locale doesn't match (default locale of the browser is fr-FR, default locale of the server is en-US)

File: packages/mui-base/src/useNumberField/useNumberField.ts [hunk 4]
```diff
@@ -0,0 +1,802 @@
...
+
+    const nextInputValue = formatNumber(value, formatOptionsRef.current);
+
+    if (nextInputValue !== inputValue) {
+      setInputValue(nextInputValue);
+    }
+  });
+
+  React.useEffect(
+    function stopAutoChangeOnUnmount() {
```
Comment (oliviertassinari) [inline packages/mui-base/src/useNumberField/useNumberField.ts:246]: Do we need to name this function?

File: packages/mui-base/src/useNumberField/useNumberField.ts [hunk 5]
```diff
@@ -0,0 +1,802 @@
...
+          return;
+        }
+
+        // We need to commit the number at this point if the input hasn't been blurred.
+        const parsedValue = parseNumber(inputValue, formatOptionsRef.current);
+        if (parsedValue !== null) {
+          rawValueRef.current = parsedValue;
+        }
+
+        event.preventDefault();
```
Comment (oliviertassinari) [inline packages/mui-base/src/useNumberField/useNumberField.ts:730]: We try to systematically document why we add preventDefault() as it tends to be disruptive (impossible for developers to remove). For example, I guess it's why

```suggestion
        // Prevent browser caret movement inside the input
        event.preventDefault();
```

File: packages/mui-base/src/useNumberField/useNumberField.ts [hunk 6]
```diff
@@ -0,0 +1,802 @@
...
+
+        const amount = getStepAmount();
+
+        if (event.key === 'ArrowUp') {
+          event.stopPropagation();
```
Comment (oliviertassinari) [inline packages/mui-base/src/useNumberField/useNumberField.ts:735]: Should we do this? It tends to be a foot gun https://css-tricks.com/dangers-stopping-event-propagation/

```suggestion
```

We rarely call this in the codebase, and always add a comment for why when we do. It makes me think of https://twitter.com/jjenzz/status/1767736778205630646

File: packages/mui-base/src/useNumberField/useNumberField.ts [hunk 7]
```diff
@@ -0,0 +1,802 @@
...
+
+  const [value, setValueUnwrapped] = useControlled<number | null>({
+    controlled: externalValue,
+    default: defaultValue,
+    name: 'NumberField',
+    state: 'value',
+  });
+
+  // We need to hide the input value during SSR to avoid a potential mismatch between the server
+  // rendered value and the client rendered value when their locales differ.
```
Comment (oliviertassinari) [inline packages/mui-base/src/useNumberField/useNumberField.ts:115]: Oh, maybe we could still render it but with `suppressHydrationWarning`? I guess we only care about this because of the warning but that warning is useless in our case?

**Review by oliviertassinari — COMMENTED** [review]
It looks like a great start 👍.

I dove into the changes, helping increase codebase consistency with new joiners, so mostly a technical review.

---

SCR-20240323-pkss

Please, let's only use @base-ui to broadcast something we want everyone to see.

File: docs/data/base/components/number-field/UnstyledNumberFieldIntroduction/css/index.tsx [hunk 8]
```diff
@@ -0,0 +1,244 @@
+import * as React from 'react';
+import { NumberField } from '@mui/base';
```
[the remark this answers is not in the document]
Comment (brijeshb42) [reply docs/data/base/components/number-field/UnstyledNumberFieldIntroduction/css/index.tsx:2]: Can we make this the default as well as teach the same in the docs for users as well. No Barrel import, import components individually from their paths.

File: docs/data/base/components/number-field/UnstyledNumberFieldIntroduction/system/index.tsx [hunk 9]
```diff
@@ -0,0 +1,216 @@
+import * as React from 'react';
+import { NumberField as BaseNumberField } from '@mui/base/NumberField';
+import { css, styled, useTheme } from '@mui/system';
```
[the remark this answers is not in the document]
Comment (brijeshb42) [reply docs/data/base/components/number-field/UnstyledNumberFieldIntroduction/system/index.tsx:3]: They can continue to import from emotion or system directly. The import path that we'll look for will be a certain pattern, like in our current case, a path ending with `/zero/styled`. No other import will be touched.
We also have the ability to override this configuration from the user's side.

File: packages/mui-base/src/useNumberField/useNumberField.ts (hunk 6 above)
Comment (atomiks) [reply packages/mui-base/src/useNumberField/useNumberField.ts:735]: For arrow keys specifically, I think yes. If you have bound arrow key listeners on the window to execute some functionality (e.g. shortcuts for actions), you don't want to propagate the event to them when using the number field.

If they want to always execute those, they can use `capture` event listeners to workaround it. I stop propagation for arrow events in Floating UI, and there has yet to be an issue about it.

File: packages/mui-base/src/useNumberField/useNumberField.ts (hunk 7 above)
Comment (atomiks) [reply packages/mui-base/src/useNumberField/useNumberField.ts:115]: There'll be a flash regardless; it depends which flash is better:

- Flash from empty field to formatted field regardless if there's a match or not
- Flash from server's formatting to the user's one. If the server matches the client, there's no flash. This indeed may be better.

File: packages/mui-base/src/useNumberField/useNumberField.ts (hunk 4 above)
Comment (atomiks) [reply packages/mui-base/src/useNumberField/useNumberField.ts:246]: It's small and clear, so probably not. I just added it for consistency since I named every effect, but I can remove this one.

File: packages/mui-base/src/NumberField/utils/parse.ts (hunk 3 above)
Comment (atomiks) [reply packages/mui-base/src/NumberField/utils/parse.ts:5]: I wasn't sure if they should be able to force a locale. It seems like an accessibility issue in that it should probably always display how the user's preference wants it to?

File: docs/data/base/pages.ts [hunk 10]
```diff
@@ -27,7 +27,7 @@ const pages: readonly MuiPage[] = [
           { pathname: '/base-ui/react-button', title: 'Button' },
           { pathname: '/base-ui/react-checkbox', title: 'Checkbox', planned: true },
           { pathname: '/base-ui/react-input', title: 'Input' },
-          { pathname: '/base-ui/react-number-input', title: 'Number Input', unstable: true },
```
[the remark this answers is not in the document]
Comment (atomiks) [reply docs/data/base/pages.ts:30]: Yeah I should probably remove the old one entirely.

File: packages/mui-base/src/NumberField/NumberFieldInput.tsx [hunk 11]
```diff
@@ -0,0 +1,62 @@
+import * as React from 'react';
+import PropTypes from 'prop-types';
+import { useForkRef } from '../utils/useForkRef';
```
[the remark this answers is not in the document]
Comment (atomiks) [reply packages/mui-base/src/NumberField/NumberFieldInput.tsx:3]: @michaldudak suggested re-exporting since he wasn't sure about the future of `@mui/utils`, so it'd lead to less refactoring needed.

File: packages/mui-base/src/useNumberField/index.ts [hunk 12]
```diff
@@ -0,0 +1,3 @@
+'use client';
```
[the remark this answers is not in the document]
Comment (atomiks) [reply packages/mui-base/src/useNumberField/index.ts:1]: Hmm, I'm not 100% sure for the hook's case. They probably have to use it inside a Client Component that they've marked already, indeed.

File: packages/mui-base/src/NumberField/utils/format.ts [hunk 13]
```diff
@@ -0,0 +1,3 @@
+export function formatNumber(value: number | null, options?: Intl.NumberFormatOptions) {
+  return typeof value === 'number' ? Intl.NumberFormat(undefined, options).format(value) : '';
```
[the remark this answers is not in the document]
Comment (atomiks) [reply packages/mui-base/src/NumberField/utils/format.ts:2]: Interesting! Will look into this. It actually does get called on every render to perform a comparison check, so caching might be necessary.

**Comment by atomiks** [comment]
## List of source code updates needed

- Fix the “magnifier” appearing on iOS when press-holding the stepper buttons.
- Add `teleportDistance` (or other name) prop to loop closer to the input compared to the viewport.
- Potentially limit the “scrub past“ distance when a `max`/`min` is specified, so it doesn't take too long to "get back".
- Potentially remove snapping behavior for `smallStep` and `largeStep`. Set `smallStep` to 0.1 by default if the formatting style is not `integer` - @colmtuite 
- Fix bug when there’s a “-“ and you can’t type “-“ again when all content has been selected to be overwritten (e.g. paste).
- Fix virtual cursor being too big when zooming (cmd+ or pinch-zoom). It should invert the scale to match the OS size.
- Fix 1px sensitivity to 2px for scrub area, and add `sensitivity` prop.
- Add `Home` and `End` key support if `min`/`max` are specified. 
- Add `displayName` to Contexts.
- Ensure all imports use the path rather than the top-level barrel.
- Cache `Intl.NumberFormat` usage.
- Match various nits/conventions pointed out by Olivier.
- When merged, use the `mergeEventHandlers` / `mergeProps` function written by Michal to significantly simplify the event handler definitions.
- Dynamically change the `inputMode="numeric"` prop for iOS when appropriate, which doesn't show a negative sign in the software keyboard, it must be `"text"`. Need to research if spinbutton props become necessary when this is changed.
- The virtual cursor should be automatically portalled to the body.
- Move `ScrubArea` logic into the `useNumberField` hook, or possibly a separate hook. Depends how granular the tree-shaking could possibly be for this functionality.

File: packages/mui-base/src/NumberField/NumberFieldContext.ts [hunk 14]
```diff
@@ -0,0 +1,19 @@
+import * as React from 'react';
+import type { UseNumberFieldReturnValue } from '../useNumberField/useNumberField.types';
+import { NumberFieldOwnerState } from './NumberField.types';
+
+export type NumberFieldContextValue = UseNumberFieldReturnValue & {
+  ownerState: NumberFieldOwnerState;
+};
+
+export const NumberFieldContext = React.createContext<NumberFieldContextValue | null>(null);
```
[the remark this answers is not in the document]
Comment (romgrk) [reply packages/mui-base/src/NumberField/NumberFieldContext.ts:9]: In the grid, I tend to use `undefined` because it's semantically good, it's the default empty value for javascript values, and it's less verbose for refs (don't need the `| null` type).

File: packages/mui-base/src/utils/useLatestRef.ts [hunk 15]
```diff
@@ -0,0 +1,14 @@
+'use client';
+import * as React from 'react';
+import { useEnhancedEffect } from './useEnhancedEffect';
+
+/**
+ * @ignore - internal hook.
+ */
+export function useLatestRef<T>(value: T) {
```
[the remark this answers is not in the document]
Comment (romgrk) [reply packages/mui-base/src/utils/useLatestRef.ts:8]: we don't have it...
image

[the remark this answers is not in the document]
Comment (romgrk) [reply packages/mui-base/src/utils/useLatestRef.ts:8]: It's fine to stay here. One issue I have with `mui-utils` is that it's a separate repo, so if a PR needs a change to an util, it can't be done in one step.

Sidenote but I didn't see the hook used in this PR, not sure if I missed it or it's not used.

[the remark this answers is not in the document]
Comment (atomiks) [reply packages/mui-base/src/utils/useLatestRef.ts:8]: It is used for the `format` prop

File: packages/mui-base/src/useNumberField/useNumberField.ts (hunk 6 above)
Comment (atomiks) [reply packages/mui-base/src/useNumberField/useNumberField.ts]: Actually, nevermind on this. The `input` element automatically stops propagation itself, so there's no need to call it on `keydown`.

File: docs/data/base/components/number-field/UnstyledNumberFieldIntroduction/css/index.js [hunk 16]
```diff
@@ -0,0 +1,244 @@
...
+import { useTheme } from '@mui/system';
+
+function useIsDarkMode() {
+  const theme = useTheme();
+  return theme.palette.mode === 'dark';
+}
+
+export default function UnstyledNumberFieldIntroduction() {
+  // Replace this with your app logic for determining dark mode
+  const isDarkMode = useIsDarkMode();
```
[the remark this answers is not in the document]
Comment (atomiks) [reply docs/data/base/components/number-field/UnstyledNumberFieldIntroduction/css/index.js:12]: All demos use this particular function, and the flash occurs throughout the whole docs

File: packages/mui-base/src/NumberField/utils/parse.ts (hunk 3 above)
Comment (atomiks) [reply packages/mui-base/src/NumberField/utils/parse.ts]: One case where it might be useful is during SSR via the [Accept-Language](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language) header. They could set a `locale` prop on the component using this, e.g. in a React Server Component?

File: packages/mui-base/src/NumberField/NumberFieldInput.tsx (hunk 11 above)
[the remark this answers is not in the document]
Comment (michaldudak) [reply packages/mui-base/src/NumberField/NumberFieldInput.tsx:3]: @oliviertassinari Doesn't this contradict what you're saying in https://github.com/mui/base-ui/pull/186#discussion_r1536646505? If we want to hide the utils package, we have to reexport the utils required to build design systems from Base UI, no?

File: packages/mui-base/src/Select/Select.test.tsx [hunk 17]
```diff
@@ -1265,82 +1265,6 @@ describe('<Select />', () => {
     expect(selectButton).to.have.text('1, 2');
   });
 
-  it('perf: does not rerender options unnecessarily', async () => {
```
Comment (atomiks) [inline packages/mui-base/src/Select/Select.test.tsx:1268]: This test appears to cause unrelated tests for `NumberInput` to fail; specifically, the `largeStep` ones that listen on the window keydown. 

Since it's only a perf test, it seems safe to delete, although maybe someone else has a better suggestion.

Comment (michaldudak) [reply packages/mui-base/src/Select/Select.test.tsx:1268]: I wouldn't delete it. It seems that there's a bigger issue with tests affecting each other and we need to figure out what's going on. I'm going to investigate it as well.

Comment (michaldudak) [reply packages/mui-base/src/Select/Select.test.tsx:1268]: For the time being, not to block your PR, you can skip this test when running on JSDOM. This way, it'll still run when tested with Karma.

Comment (michaldudak) [reply packages/mui-base/src/Select/Select.test.tsx:1268]: I found out that we can isolate the tests by adding the `--parallel` flag to mocha (this can also speed them up). However, I haven't gotten to the root cause of these issues yet.

File: packages/mui-base/test/conformanceTests/className.tsx [hunk 18]
```diff
@@ -15,8 +15,8 @@ export function testClassName(
     }
 
     it('should apply the className when passed as a string', async () => {
-      const { container } = await render(React.cloneElement(element, { className: 'test-class' }));
-      expect(container.firstElementChild?.className).to.contain('test-class');
+      await render(React.cloneElement(element, { className: 'test-class' }));
+      expect(document.querySelector('.test-class')).not.to.equal(null);
```
Comment (atomiks) [inline packages/mui-base/test/conformanceTests/className.tsx:19]: This + `renderProp` conformance test changed to support portals

File: packages/mui-base/src/utils/clamp.ts [hunk 19]
```diff
@@ -0,0 +1 @@
+export { default as clamp } from '@mui/utils/clamp';
```
Comment (mnajdova) [inline packages/mui-base/src/utils/clamp.ts:1]: Can we do the utils changes in a separate PR? It will make the review easier.

File: packages/mui-base/src/useNumberField/useNumberField.ts (hunk 7 above)
Comment (mnajdova) [reply packages/mui-base/src/useNumberField/useNumberField.ts:115]: > Flash from server's formatting to the user's one. If the server matches the client, there's no flash. This indeed may be better.

👍

**Review by mnajdova — COMMENTED** [review]
Looks really good 👌

File: packages/mui-base/src/NumberField/NumberField.tsx [hunk 20]
```diff
@@ -0,0 +1,200 @@
...
+    required = false,
+    disabled = false,
+    invalid = false,
+    readOnly = false,
+    autoFocus,
+    name,
+    value,
+    onChange,
+    allowWheelScrub,
+    render: renderProp,
```
[the remark this answers is not in the document]
Comment (atomiks) [reply packages/mui-base/src/NumberField/NumberField.tsx:43]: We went with the `??` fallback because it avoids requiring a default when generating docs which is too difficult with the generic `BaseUiCommonComponentProps` due to the polymorphic components.

File: packages/mui-base/src/NumberField/NumberField.tsx [hunk 21]
```diff
@@ -0,0 +1,200 @@
...
+    className,
+    ...otherProps
+  } = props;
+  const render = renderProp ?? defaultRender;
+
+  const numberField = useNumberField(props);
```
[the remark this answers is not in the document]
Comment (atomiks) [reply packages/mui-base/src/NumberField/NumberField.tsx:48]: In this case, `ownerState` is a partially derived version of `useNumberField`, so it can't be called with it. The default values of the hook match the component.

File: packages/mui-base/src/utils/clamp.ts (hunk 19 above)
Comment (atomiks) [reply packages/mui-base/src/utils/clamp.ts:1]: I think at this stage, it's easier if the utils are kept in this PR. To keep it working before rebasing, I'd have to import directly from `@mui/utils` temporarily, right? I can remember to do utils separately for next time.

**Comment by colmtuite** [comment]
Decisions from a recent call:

- Agreed to just change the scrub min/max thing. There was one other issue mentioned, but James couldn't remember what it was. So the plan is to change it, then test again.
- Do some research to see if cmd/ctrl is the best key for `smallStep`. Perhaps `alt/option` is better?
- Internationalisation: passing functions and stuff needs to be added.

**Comment by atomiks** [comment]
@colmtuite 

- Already changed
- Given only Chakra seems to have this, I couldn't find any info about it. I don't think it matters really — I asked Claude and its first thought was `Alt` not `Meta`, if that has any bearing. But it said it doesn't really matter overall.

> Internationalisation: passing functions and stuff needs to be added.

Can you elaborate more here? The `format` prop doesn't accept a function in that it only accepts `Intl.NumberFormatOptions`, but do you want to enable them to format the input however they like as well? (I believe Chakra does this.) I think this can be done if they specify `value` manually on `NumberField.Input` as it will override our internal prop, but this may cause issues (that I will need to investigate). If they do that as well, it will force them to make the component controlled since they'll need access to the number `value`.

We might be missing props similar to `validate` (accepts a function) and `validationBehavior` (string) from `react-aria`, however.

**Comment by colmtuite** [comment]
@atomiks 

> I asked Claude and its first thought was Alt

Ok yeah my first thought was `Alt` also. If that's the only info we have, and both point to `Alt`, I guess let's go with `Alt`.

> do you want to enable them to format the input however they like as well

No this was just a note I took from our call, not sure what you meant when you were talking about formatting, internationalisation, and functions. I remember you saying some piece of work around internationalisation is still incomplete?

**Comment by atomiks** [comment]
@colmtuite 

> Ok yeah my first thought was Alt also. If that's the only info we have, and both point to Alt, I guess let's go with Alt.

Alright, will change 👍 

> I remember you saying some piece of work around internationalisation is still incomplete?

Yeah there were some bugs remaining with the parsing and validation functions, but I should have fixed most of them in the recent commits. However these are only internal and not part of any API.

**Review by colmtuite — APPROVED** [review]

File: docs/data/base/components/number-field/number-field.md [hunk 22]
```diff
@@ -0,0 +1,235 @@
...
+
+The `value` prop holds the number value, and `onChange` is called when it updates:
+
+```jsx
+function App() {
+  const [value, setValue] = useState(0);
+  return (
+    <NumberField value={value} onChange={setValue}>
+      <NumberField.Group>
+        <NumberField.Decrement>&minus;</NumberField.Decrement>
```
Comment (michaldudak) [inline docs/data/base/components/number-field/number-field.md:82]: I'm curious, why not `-`?

File: docs/data/base/components/number-field/number-field.md [hunk 23]
```diff
@@ -0,0 +1,235 @@
...
+  </NumberField.Group>
+</NumberField>
+```
+
+In the above example, the numbers are snapped to multiples of `step` starting from the `min` value: `2`, `7`, `12`, `17` and so on.
+
+The `largeStep` and `smallStep` props can be specified to change the step when a modifier key is held:
+
+- `largeStep` is used when <kbd>shift</kbd> is held, incrementing and snapping to multiples of `10`.
+- `smallStep` is used when <kbd>meta</kbd> (<kbd>cmd</kbd> or <kbd>ctrl</kbd>) is held, incrementing and snapping to multiples of `0.1`.
```
Comment (michaldudak) [inline docs/data/base/components/number-field/number-field.md:140]:
```suggestion
- `smallStep` is used when <kbd>Alt</kbd> is held, incrementing and snapping to multiples of `0.1`.
```

File: packages/mui-base/src/useNumberField/useScrub.ts [hunk 24]
```diff
@@ -0,0 +1,270 @@
...
+import { ownerDocument, ownerWindow } from '../utils/owner';
+import { useLatestRef } from '../utils/useLatestRef';
+import { isWebKit } from '../utils/detectBrowser';
+import { DEFAULT_STEP } from './constants';
+import { ScrubHandle, ScrubParams } from './useScrub.types';
+import { getViewportRect, subscribeToVisualViewportResize } from './utils';
+import { mergeReactProps } from '../utils/mergeReactProps';
+
+/**
+ * @ignore - internal hook.
```
[the remark this answers is not in the document]
Comment (atomiks) [reply packages/mui-base/src/useNumberField/useScrub.ts:13]: No as it's just an internal hook to place some of the functionality in its own hook

File: docs/data/base/components/number-field/number-field.md (hunk 22 above)
Comment (atomiks) [reply docs/data/base/components/number-field/number-field.md:82]: &minus is wider and looks more in proportion with `+` 😅
