### PR TITLE
[Menu, Select] Add the `modal` prop

### LINKED ISSUE #1078: [menu] Submenus can't be hovered
# Bug report

## Current behavior

https://github.com/user-attachments/assets/3d8df2e9-c7a1-4a27-bceb-94cab77956d6

<summary>
View code

<details>

Pop this into the CSS Modules menu demo

```tsx
import * as React from 'react';
import { Menu } from '@base-ui-components/react/menu';
import styles from './index.module.css';

export default function ExampleMenu() {
  return (
    <Menu.Root>
      <Menu.Trigger className={styles.Button}>
        Song <ChevronDownIcon className={styles.ButtonIcon} />
      </Menu.Trigger>
      <Menu.Portal>
        <Menu.Positioner className={styles.Positioner} sideOffset={8}>
          <Menu.Popup className={styles.Popup}>
            <Menu.Arrow className={styles.Arrow}>
              <ArrowSvg />
            </Menu.Arrow>
            <Menu.Item className={styles.Item}>Add to Library</Menu.Item>
            <Menu.Item className={styles.Item}>Add to Playlist</Menu.Item>
            <Menu.Separator className={styles.Separator} />
            <Menu.Item className={styles.Item}>Play Next</Menu.Item>
            <Menu.Item
              onClick={() => console.log('play last')}
              className={styles.Item}
            >
              Play Last
            </Menu.Item>

            <Menu.Root>
              <Menu.SubmenuTrigger className={styles.Item}>Sub</Menu.SubmenuTrigger>
              <Menu.Portal>
                <Menu.Positioner
                  className={styles.Positioner}
                  align="start"
                  side="right"
                  sideOffset={2}
                >
                  <Menu.Popup className={styles.Popup}>
                    <Menu.Item className={styles.Item}>Add to Library</Menu.Item>
                    <Menu.Item className={styles.Item}>Add to Playlist</Menu.Item>
                    <Menu.Separator className={styles.Separator} />
                    <Menu.Item className={styles.Item}>Play Next</Menu.Item>
                    <Menu.Item className={styles.Item}>Play Last</Menu.Item>
                    <Menu.Separator className={styles.Separator} />
                    <Menu.Item className={styles.Item}>Favorite</Menu.Item>
                    <Menu.Item className={styles.Item}>Share</Menu.Item>
                  </Menu.Popup>
                </Menu.Positioner>
              </Menu.Portal>
            </Menu.Root>

            <Menu.Separator className={styles.Separator} />
            <Menu.Item className={styles.Item}>Favorite</Menu.Item>
            <Menu.Item className={styles.Item}>Share</Menu.Item>
          </Menu.Popup>
        </Menu.Positioner>
      </Menu.Portal>
    </Menu.Root>
  );
}

function ArrowSvg(props: React.ComponentProps<'svg'>) {
  return (
    <svg width="20" height="10" viewBox="0 0 20 10" fill="none" {...props}>
      <path
        d="M9.66437 2.60207L4.80758 6.97318C4.07308 7.63423 3.11989 8 2.13172 8H0V10H20V8H18.5349C17.5468 8 16.5936 7.63423 15.8591 6.97318L11.0023 2.60207C10.622 2.2598 10.0447 2.25979 9.66437 2.60207Z"
        className={styles.ArrowFill}
      />
      <path
        d="M8.99542 1.85876C9.75604 1.17425 10.9106 1.17422 11.6713 1.85878L16.5281 6.22989C17.0789 6.72568 17.7938 7.00001 18.5349 7.00001L15.89 7L11.0023 2.60207C10.622 2.2598 10.0447 2.2598 9.66436 2.60207L4.77734 7L2.13171 7.00001C2.87284 7.00001 3.58774 6.72568 4.13861 6.22989L8.99542 1.85876Z"
        className={styles.ArrowOuterStroke}
      />
      <path
        d="M10.3333 3.34539L5.47654 7.71648C4.55842 8.54279 3.36693 9 2.13172 9H0V8H2.13172C3.11989 8 4.07308 7.63423 4.80758 6.97318L9.66437 2.60207C10.0447 2.25979 10.622 2.2598 11.0023 2.60207L15.8591 6.97318C16.5936 7.63423 17.5468 8 18.5349 8H20V9H18.5349C17.2998 9 16.1083 8.54278 15.1901 7.71648L10.3333 3.34539Z"
        className={styles.ArrowInnerStroke}
      />
    </svg>
  );
}

function ChevronDownIcon(props: React.ComponentProps<'svg'>) {
  return (
    <svg width="10" height="10" viewBox="0 0 10 10" fill="none" {...props}>
      <path d="M1 3.5L5 7.5L9 3.5" stroke="currentcolor" strokeWidth="1.5" />
    </svg>
  );
}
```
</details>
</summary>

## Expected behavior

It works

**Search keywords**:

### PR DESCRIPTION
**Pull request by michaldudak**
- Added the `modal` prop to Menu and Select
- Refactored the Menu to be more in line with Select regarding click-drag-release support

Closes #1078

### CODE REVIEW

File: packages/react/src/select/root/SelectRoot.tsx [hunk 1]
```diff
@@ -32,6 +32,7 @@ const SelectRoot: SelectRoot = function SelectRoot<Value>(
     disabled = false,
     readOnly = false,
     required = false,
+    modal = false,
   } = props;
```
Comment (atomiks) [inline packages/react/src/select/root/SelectRoot.tsx:36]: The problem with select modality is that it prevents touch screen readers from being able to escape it without selecting anything.

File: packages/react/src/select/popup/SelectPopup.tsx [hunk 2]
```diff
@@ -91,8 +91,9 @@ const SelectPopup = React.forwardRef(function SelectPopup(
       )}
       <FloatingFocusManager
         context={positioner.positionerContext}
-        modal={false}
+        modal={modal}
         disabled={!mounted}
+        outsideElementsInert
       >
```
Comment (atomiks) [inline packages/react/src/select/popup/SelectPopup.tsx:97]:
```suggestion
      <FloatingFocusManager
        context={positioner.positionerContext}
        modal={false}
        modal={modal}
        disabled={!mounted}
        outsideElementsInert
        visuallyHiddenDismiss={modal ? 'Dismiss popup' : undefined}
      >
```

Comment (michaldudak) [reply packages/react/src/select/popup/SelectPopup.tsx:97]: :+1: I'm adding it to the Menu as well. We could make the text configurable in the future if needed.

File: docs/data/components/select/select.mdx [hunk 3]
```diff
@@ -110,6 +110,18 @@ The `Select.ItemIndicator` subcomponent renders an indicator inside an option to
...
+
+By default, the Select is non-modal, so elements outside it can be interacted with.
+To make it modal, use the `modal` prop.
+You may also add a backdrop to the modal Select by using the `Select.Backdrop` component, to indicate that the outside elements are inert.
+
+```jsx
+<Select.Root modal>
+  <Select.Backdrop />
+</Select.Root>
+```
```
Comment (atomiks) [inline docs/data/components/select/select.mdx:123]: I guess if `alignItemToTrigger` is true, it should be `modal` by default. The reason is you can scroll the background but it doesn't reposition itself unlike with regular popup-aligned anchoring, plus scrolling is locked which seems like it should be modal-only feature

Comment (michaldudak) [reply docs/data/components/select/select.mdx:123]: I suppose we could even make it modal by default all the time (that's how native macOS 
 controls work). cc @vladmoroz

**Comment by michaldudak** [comment]
Converting it back to draft as there are issues with nested menus

File: packages/react/src/select/root/useSelectRoot.ts [hunk 4]
```diff
@@ -360,6 +363,11 @@ export namespace useSelectRoot {
      * The transition status of the Select.
      */
     transitionStatus?: TransitionStatus;
+    /**
+     * Whether the select is modal.
+     * @default true
+     */
```
Comment (vladmoroz) [inline packages/react/src/select/root/useSelectRoot.ts:369]: I've just added a new description for the modal prop across the board
https://github.com/mui/base-ui/blob/master/packages/react/src/dialog/root/useDialogRoot.ts#L167-L171

Comment (michaldudak) [reply packages/react/src/select/root/useSelectRoot.ts]: :+1: Updated

**Comment by michaldudak** [comment]
This requires https://github.com/floating-ui/floating-ui/pull/3160 to be released to fully work properly.

**Comment by atomiks** [comment]
`@floating-ui/react@0.27.1` is out

File: packages/react/src/menu/popup/MenuPopup.tsx [hunk 5]
```diff
@@ -75,7 +76,10 @@ const MenuPopup = React.forwardRef(function MenuPopup(
       context={floatingContext}
       modal={false}
       initialFocus={nested ? -1 : 0}
+      returnFocus
       disabled={!mounted}
+      visuallyHiddenDismiss={modal ? 'Dismiss popup' : undefined}
+      order={!nested ? ['content', 'reference'] : undefined}
```
Comment (atomiks) [inline packages/react/src/menu/popup/MenuPopup.tsx:82]: What's `order` for? I notice the popup doesn't take focus on click with a pointer - not sure if this matters though.

File: packages/react/src/select/positioner/useSelectPositioner.ts [hunk 6]
```diff
@@ -15,9 +15,9 @@ import { useScrollLock } from '../../utils/useScrollLock';
 export function useSelectPositioner(
   params: useSelectPositioner.Parameters,
 ): useSelectPositioner.ReturnValue {
-  const { open, alignItemToTrigger, mounted, triggerElement } = useSelectRootContext();
+  const { open, alignItemToTrigger, mounted, triggerElement, modal } = useSelectRootContext();
 
-  useScrollLock(alignItemToTrigger && mounted, triggerElement);
+  useScrollLock(modal && open, triggerElement);
```
Comment (atomiks) [inline packages/react/src/select/positioner/useSelectPositioner.ts:20]: Is `alignItemToTrigger=true` always forced to be `modal` mode? It doesn't support non-scroll locked mode, even if they wanted it

File: packages/react/src/menu/popup/MenuPopup.tsx (hunk 5 above)
Comment (michaldudak) [reply packages/react/src/menu/popup/MenuPopup.tsx:82]: This makes the trigger not receive the data-floating-ui-inert attribute, so it can properly fire its click handler. Without it, it becomes inert (via poiner-events) after mousedown, so mouseup doesn't fire.

File: packages/react/src/select/positioner/useSelectPositioner.ts (hunk 6 above)
Comment (michaldudak) [reply packages/react/src/select/positioner/useSelectPositioner.ts:20]: OK, I'll make it `(alignItemToTrigger || modal) && open`, then

File: packages/react/src/menu/popup/MenuPopup.tsx (hunk 5 above)
Comment (atomiks) [reply packages/react/src/menu/popup/MenuPopup.tsx:82]: I think it's a good idea to force `initialFocus` on the Popup if it's `undefined` now. It removes the default `:focus-visible` outline on the trigger

Comment (atomiks) [reply packages/react/src/menu/popup/MenuPopup.tsx:82]: Also, shouldn't select's trigger need it?

Comment (michaldudak) [reply packages/react/src/menu/popup/MenuPopup.tsx:82]: > Also, shouldn't select's trigger need it?

It doesn't have the click handler, so we don't need it, but it might be a good idea anyway to make external click events work

Comment (michaldudak) [reply packages/react/src/menu/popup/MenuPopup.tsx:82]: > I think it's a good idea to force initialFocus on the Popup if it's undefined now. It removes the default :focus-visible outline on the trigger

Do you mean `initialFocus={nested ? -1 : popupRef}`?

Comment (atomiks) [reply packages/react/src/menu/popup/MenuPopup.tsx:82]: Something like that yes

File: packages/react/src/select/root/useSelectRoot.ts [hunk 7]
```diff
@@ -168,7 +169,9 @@ export function useSelectRoot<T>(params: useSelectRoot.Parameters<T>): useSelect
     event: 'mousedown',
   });
 
-  const dismiss = useDismiss(floatingRootContext);
+  const dismiss = useDismiss(floatingRootContext, {
+    bubbles: false,
+  });
```
Comment (atomiks) [inline packages/react/src/select/root/useSelectRoot.ts:174]: Pressing `esc` in Select seems to still dismiss the outer Dialog in
https://deploy-preview-991--base-ui.netlify.app/experiments/popups-in-popups

Comment (michaldudak) [reply packages/react/src/select/root/useSelectRoot.ts:174]: Yeah, I noticed. Also pressing outside closes all the popups at once.
It seems that this setting works only within a tree?

Comment (atomiks) [reply packages/react/src/select/root/useSelectRoot.ts:174]: `esc` should work without a tree, but outside press can't (though that's usually a good thing anyway in my view)

**Review by atomiks — APPROVED** [review]
