### PR TITLE
[navigation menu] Ensure submenu triggers participate in composite list

### LINKED ISSUE #3343: [navigation-menu] Arrow navigation skipping the submenu trigger
# Bug report

## Current behavior

The the submenu trigger is not focusable with arrow navigation, e.g. https://base-ui.com/react/components/navigation-menu#nested-submenus, try focusing the Handbook item. 

## Expected behavior

It should be focusable with arrow navigation

### PR DESCRIPTION
**Pull request by atomiks**
- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/base-ui/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).

Fixes #3343

### CODE REVIEW

File: packages/react/src/navigation-menu/list/NavigationMenuList.tsx [hunk 1]
```diff
@@ -65,14 +66,34 @@ export const NavigationMenuList = React.forwardRef(function NavigationMenuList(
...
+  // in the parent Content's composite navigation context. Also skip the onKeyDown
+  // handler that blocks propagation so arrow keys can reach the parent CompositeRoot.
+  const element = useRenderElement('ul', componentProps, {
+    state,
+    ref: forwardedRef,
+    props,
+    enabled: nested,
+  });
+
+  if (nested) {
```
Comment (mnajdova) [inline packages/react/src/navigation-menu/list/NavigationMenuList.tsx:84]: I would move the logic in the return element below, it will be much clear what's different in the return between the two branches.

Comment (atomiks) [reply packages/react/src/navigation-menu/list/NavigationMenuList.tsx:84]: Not sure what you mean? Hooks can't be called conditionally

**Comment by atomiks** [comment]
@mnajdova <kbd>ArrowRight</kbd> was working, it's not meant to open the submenu if that's what you meant. Fixed <kbd>ArrowUp</kbd>/<kbd>ArrowDown</kbd>

**Comment by mnajdova** [comment]
> @mnajdova ArrowRight was working, it's not meant to open the submenu if that's what you meant. 

I am pretty sure it did nothing (did not move to the first element). Anyways, all works good now 👌

File: packages/react/src/navigation-menu/list/NavigationMenuList.tsx (hunk 1 above)
Comment (mnajdova) [reply packages/react/src/navigation-menu/list/NavigationMenuList.tsx:84]: I meant conditionally render element or CompositeRoot on line 70. But never mind, it's fine.
