### PR TITLE
[dialog] Fix closing after pointer lock exit in Firefox

### LINKED ISSUE #3306: [NumberInput + Dialog] scrolling `ScrubArea` with mouse closes the Dialog on mouse release
# Bug report

## Current behavior

If the `NumberInput` component is in a `Dialog`, changing the value by scrolling with `ScrubArea` will also closes the dialog when i stop holding the mouse, rendering the component momentarily unusable

## Expected behavior

releasing mouse (and potentially thumb on mobile devices) should not propagate events to dialogs

## Reproducible example

https://stackblitz.com/edit/awgfv3sl?file=src%2FApp.tsx

## Base UI version

v1.0.0-beta.6

## Which browser are you using?

Firefox

## Which OS are you using?

Linux

## Which assistive tech are you using (if applicable)?

None

## Additional context

None

### PR DESCRIPTION
**Pull request by atomiks**
- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/base-ui/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).

After pointer lock exit, Firefox fires a click event on `<body>` (unlike Chrome), so it's an "outside press" (incorrectly)

`NumberField.ScrubArea` calls `.preventDefault()` in `onPointerDown` (to avoid stealing focus from the input) but this blocks the `handlePressedInside` call which prevents the outside click of popovers and dialogs from firing if the press started inside but ended outside.

Fixes #3306 - https://stackblitz.com/edit/awgfv3sl-g3rdti11

### CODE REVIEW

File: packages/react/src/floating-ui-react/hooks/useDismiss.ts [hunk 1]
```diff
@@ -691,8 +691,10 @@ export function useDismiss(
       onKeyDown: closeOnEscapeKeyDown,
       onMouseDown: handlePressedInside,
       onMouseUp: handlePressedInside,
-      onPointerDownCapture: markInsideReactTree,
-      onMouseDownCapture: markInsideReactTree,
+      onPointerDownCapture(event) {
```
Comment (mnajdova) [inline packages/react/src/floating-ui-react/hooks/useDismiss.ts]: Please add a comment explaining why this is added, it's something that can easily be broken in the future, especially as it is one browser edge case.

Comment (atomiks) [reply packages/react/src/floating-ui-react/hooks/useDismiss.ts]: The change itself is not necessarily Firefox-only, but it happens to fix a bug on Firefox. I adjusted the code and added a more general comment as to why `onPointerDown: handlePressedInside` should be added.
